"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";

type Language = "en" | "ru";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.code": "Code",
    "nav.contacts": "Contacts",
    "hero.greeting": "Hi, I'm",
    "hero.name": "KusokMedi",
    "hero.title": "Developer / Programmer",
    "hero.description": "I create websites, bots, automation and digital solutions. Specialization: Python, React, Node.js, Linux.",
    "hero.cta": "View Projects",
    "terminal.line1": "I'm KusokMedi :)",
    "terminal.line2": "Developer ready to turn your idea into code!",
    "terminal.line3": "",
    "terminal.line4": "I can create a Bot, Website or Application for you,",
    "terminal.line5": "help with hosting, improve your current project,",
    "terminal.line6": "integrate AI or other services into your product!",
    "terminal.line7": "",
    "terminal.line8": "Let's create something cool!",
    "about.title": "About Me",
    "about.subtitle": "Who I am",
    "about.heading": "I create digital products that **matter**",
    "about.text1": "I am a developer who doesn't limit myself to one stack. Websites, Telegram bots, APIs, server infrastructure - I understand and do it all. I quickly get into context and start working.",
    "about.text2": "I specialize in Python, React, Node.js and Linux. I take a project from concept to production, working with the full stack. My approach: understand the problem, choose the right tools and build something that works reliably.",
    "highlight.experience": "Experience",
    "highlight.experience.value": "3+ years",
    "highlight.experience.desc": "Commercial development and work on projects of different scales - from startups to large systems",
    "highlight.projects": "Projects",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Completed projects in various fields: from Telegram bots to server infrastructure",
    "highlight.tech": "Technologies",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Programming languages, frameworks and tools I master at a professional level",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits on GitHub during all the time of active open-source and personal projects development",
    "services.title": "Services",
    "services.subtitle": "What I do",
    "services.heading": "What I can do **for you**",
    "services.description": "Full development cycle - from concept to deployment. I work with the entire stack to create a ready-made solution.",
    "service.web.title": "Web Development",
    "service.web.desc": "Websites, web applications and admin panels.",
    "service.web.detail1": "Responsive websites",
    "service.web.detail2": "Web applications",
    "service.web.detail3": "Admin panels",
    "service.web.detail4": "Landing pages",
    "service.bots.title": "Bot Development",
    "service.bots.desc": "Telegram bots, Discord bots and automation.",
    "service.bots.detail1": "Telegram bots",
    "service.bots.detail2": "Discord bots",
    "service.bots.detail3": "Chat automation",
    "service.bots.detail4": "AI integration",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, databases and server logic.",
    "service.backend.detail1": "REST and GraphQL API",
    "service.backend.detail2": "Database design",
    "service.backend.detail3": "Authentication",
    "service.backend.detail4": "Microservices",
    "service.linux.title": "Linux / Servers",
    "service.linux.desc": "Server configuration, optimization and automation.",
    "service.linux.detail1": "Server configuration",
    "service.linux.detail2": "Docker deployment",
    "service.linux.detail3": "CI/CD pipelines",
    "service.linux.detail4": "Monitoring",
    "service.programs.title": "Programs",
    "service.programs.desc": "Utilities, scripts and programs for any tasks.",
    "service.programs.detail1": "CLI tools",
    "service.programs.detail2": "Automation scripts",
    "service.programs.detail3": "Desktop utilities",
    "service.programs.detail4": "Data processing",
    "service.audit.title": "Audit and Consulting",
    "service.audit.desc": "Refactoring, optimization and architectural solutions.",
    "service.audit.detail1": "Code and project audit",
    "service.audit.detail2": "Performance optimization",
    "service.audit.detail3": "System architecture",
    "service.audit.detail4": "Technical documentation",
    "service.hosting.title": "Hosting and Deploy",
    "service.hosting.desc": "Hosting your sites, bots and scripts on the server. Turnkey solutions launch.",
    "service.hosting.detail1": "Ready scripts and bots hosting",
    "service.hosting.detail2": "VPS/VDS and hosting setup",
    "service.hosting.detail3": "Domains and SSL certificates",
    "service.hosting.detail4": "Project migration",
    "service.support.title": "Support and Maintenance",
    "service.support.desc": "Technical support for your projects. Prompt bug fixes and stability control.",
    "service.support.detail1": "Error and bug fixing",
    "service.support.detail2": "Dependencies and systems update",
    "service.support.detail3": "Regular backups setup",
    "service.support.detail4": "24/7 availability monitoring",
    "service.api.title": "API and Services Integration",
    "service.api.desc": "Connecting your sites and programs with external systems for business process automation.",
    "service.api.detail1": "Payment systems connection",
    "service.api.detail2": "CRM integration (amoCRM, Bitrix24)",
    "service.api.detail3": "Messenger notifications setup",
    "service.api.detail4": "Google Sheets synchronization",
    "projects.title": "Projects",
    "projects.subtitle": "My work",
    "projects.heading": "**Featured** works",
    "projects.description": "Real projects created from scratch - each solves specific problems using the right technologies.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot for anonymous messages right in Telegram. Create your link - anyone who follows it will be able to send you an anonymous message.",
    "project.anonspeak.cta": "Open bot",
    "project.anonspeak.feat1": "Create your anonymous link",
    "project.anonspeak.feat2": "Reply to anonymous messages",
    "project.anonspeak.feat3": "Block unwanted users",
    "project.anonspeak.feat4": "Message statistics",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Support bot for Minecraft studio BestDev. Order a plugin, build, consultation or a turnkey solution.",
    "project.bestdev.cta": "Open bot",
    "project.bestdev.feat1": "Order plugins and builds turnkey",
    "project.bestdev.feat2": "Project consultations",
    "project.bestdev.feat3": "Dev team applications",
    "project.bestdev.feat4": "Ready products and solutions",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Vanilla Minecraft server 1.21.11 with economy. /sell, auction, TPA and no extra additions - everything is as vanilla as possible.",
    "project.gridmc.cta": "Join Discord",
    "project.gridmc.feat1": "Economy with /sell and /ah",
    "project.gridmc.feat2": "No /spawn and extra junk",
    "project.gridmc.feat3": "One world without rules",
    "project.gridmc.feat4": "Maximum vanilla gameplay",
    "contact.title": "Contact",
    "contact.subtitle": "Get in touch",
    "contact.heading": "Let's create something **together**",
    "contact.text": "Have a project or just want to chat? Write to me on Telegram - I'm always ready to discuss and implement your project at a great price.",
    "contact.button": "Write to Telegram",
    "github.title": "Code",
    "github.subtitle": "GitHub repos",
    "footer.rights": "All rights reserved.",
    "notFound.title": "Page not found",
    "notFound.text": "This page does not exist. It may have been moved or deleted.",
    "notFound.button": "Go home",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "Обо мне",
    "nav.services": "Услуги",
    "nav.projects": "Проекты",
    "nav.code": "Код",
    "nav.contacts": "Контакты",
    "hero.greeting": "Привет, я",
    "hero.name": "KusokMedi",
    "hero.title": "Разработчик / Программист",
    "hero.description": "Создаю сайты, ботов, автоматизацию и цифровые решения. Специализация: Python, React, Node.js, Linux.",
    "hero.cta": "Смотреть проекты",
    "terminal.line1": "Я - KusokMedi :)",
    "terminal.line2": "Разработчик, готовый воплотить вашу идею в код!",
    "terminal.line3": "",
    "terminal.line4": "Я могу создать для вас Бота, Сайт или Приложение,",
    "terminal.line5": "помочь с хостингом, улучшить текущий проект,",
    "terminal.line6": "интегрировать ИИ или другие сервисы в ваш продукт!",
    "terminal.line7": "",
    "terminal.line8": "Давайте создадим что-то крутое!",
    "about.title": "Обо мне",
    "about.subtitle": "Кто я",
    "about.heading": "Создаю цифровые продукты, которые **имеют значение**",
    "about.text1": "Я разработчик, который не ограничивается одним стеком. Сайты, Telegram-боты, API, серверная инфраструктура - я разбираюсь и делаю. Быстро вхожу в контекст и приступаю к работе.",
    "about.text2": "Специализируюсь на Python, React, Node.js и Linux. Беру проект от концепции до продакшена, работаю с полным стеком. Мой подход: понять проблему, выбрать правильные инструменты и построить то, что надежно работает.",
    "highlight.experience": "Опыт",
    "highlight.experience.value": "3+ года",
    "highlight.experience.desc": "Коммерческой разработки и работы над проектами разного масштаба - от стартапов до крупных систем",
    "highlight.projects": "Проекты",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Завершённых проектов в самых разных сферах: от Telegram-ботов до серверной инфраструктуры",
    "highlight.tech": "Технологии",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Языков программирования, фреймворков и инструментов, которыми я владею на профессиональном уровне",
    "highlight.commits": "Коммиты",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Коммитов на GitHub за всё время активной разработки open-source и личных проектов",
    "services.title": "Услуги",
    "services.subtitle": "Чем занимаюсь",
    "services.heading": "Что я могу **для вас сделать**",
    "services.description": "Полный цикл разработки - от концепции до деплоя. Работаю со всем стеком, чтобы создать готовое решение.",
    "service.web.title": "Веб-разработка",
    "service.web.desc": "Сайты, веб-приложения и админ-панели.",
    "service.web.detail1": "Адаптивные сайты",
    "service.web.detail2": "Веб-приложения",
    "service.web.detail3": "Админ-панели",
    "service.web.detail4": "Лендинги",
    "service.bots.title": "Разработка ботов",
    "service.bots.desc": "Telegram-боты, Discord-боты и автоматизация.",
    "service.bots.detail1": "Telegram-боты",
    "service.bots.detail2": "Discord-боты",
    "service.bots.detail3": "Автоматизация чатов",
    "service.bots.detail4": "Интеграция AI",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, базы данных и серверная логика.",
    "service.backend.detail1": "REST и GraphQL API",
    "service.backend.detail2": "Проектирование БД",
    "service.backend.detail3": "Аутентификация",
    "service.backend.detail4": "Микросервисы",
    "service.linux.title": "Linux / Серверы",
    "service.linux.desc": "Настройка, оптимизация и автоматизация серверов.",
    "service.linux.detail1": "Конфигурация серверов",
    "service.linux.detail2": "Деплой через Docker",
    "service.linux.detail3": "CI/CD пайплайны",
    "service.linux.detail4": "Мониторинг",
    "service.programs.title": "Программы",
    "service.programs.desc": "Утилиты, скрипты и программы для любых задач.",
    "service.programs.detail1": "CLI-инструменты",
    "service.programs.detail2": "Скрипты автоматизации",
    "service.programs.detail3": "Десктоп-утилиты",
    "service.programs.detail4": "Обработка данных",
    "service.audit.title": "Аудит и Консалтинг",
    "service.audit.desc": "Рефакторинг, оптимизация и архитектурные решения.",
    "service.audit.detail1": "Аудит кода и проектов",
    "service.audit.detail2": "Оптимизация производительности",
    "service.audit.detail3": "Архитектура систем",
    "service.audit.detail4": "Техническая документация",
    "service.hosting.title": "Хостинг и Деплой",
    "service.hosting.desc": "Размещение ваших сайтов, ботов и скриптов на сервере. Запуск готовых решений «под ключ».",
    "service.hosting.detail1": "Размещение готовых скриптов и ботов",
    "service.hosting.detail2": "Настройка VPS / VDS и хостинга",
    "service.hosting.detail3": "Привязка доменов и SSL-сертификатов",
    "service.hosting.detail4": "Перенос проектов на новые сервера",
    "service.support.title": "Поддержка и Обслуживание",
    "service.support.desc": "Техническое сопровождение ваших проектов. Оперативное исправление багов и контроль стабильности.",
    "service.support.detail1": "Исправление ошибок и багов",
    "service.support.detail2": "Обновление зависимостей и систем",
    "service.support.detail3": "Настройка регулярных бэкапов",
    "service.support.detail4": "Мониторинг доступности 24/7",
    "service.api.title": "Интеграция API и Сервисов",
    "service.api.desc": "Связка ваших сайтов и программ с внешними системами для автоматизации бизнес-процессов.",
    "service.api.detail1": "Подключение платежных систем",
    "service.api.detail2": "Интеграция с CRM (amoCRM, Битрикс24)",
    "service.api.detail3": "Настройка уведомлений в мессенджеры",
    "service.api.detail4": "Синхронизация с Google Таблицами",
    "projects.title": "Проекты",
    "projects.subtitle": "Мои работы",
    "projects.heading": "**Избранные** работы",
    "projects.description": "Реальные проекты, созданные с нуля - каждый решает конкретные задачи с помощью правильных технологий.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Бот для анонимных сообщений прямо в Telegram. Создай свою ссылку - любой, кто перейдёт по ней, сможет написать тебе анонимное сообщение.",
    "project.anonspeak.cta": "Открыть бота",
    "project.anonspeak.feat1": "Создание своей анонимной ссылки",
    "project.anonspeak.feat2": "Ответ на анонимные сообщения",
    "project.anonspeak.feat3": "Блокировка нежелательных пользователей",
    "project.anonspeak.feat4": "Статистика сообщений",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Бот поддержки для Minecraft-студии BestDev. Закажи плагин, сборку, консультацию или готовое решение под ключ.",
    "project.bestdev.cta": "Открыть бота",
    "project.bestdev.feat1": "Заказ плагинов и сборок под ключ",
    "project.bestdev.feat2": "Консультации по проектам",
    "project.bestdev.feat3": "Заявки в команду разработки",
    "project.bestdev.feat4": "Готовые товары и решения",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Ванильный Minecraft-сервер 1.21.11 с экономикой. /sell, аукцион, TPA и никаких лишних дополнений - всё максимально как в ванилле.",
    "project.gridmc.cta": "Зайти в Discord",
    "project.gridmc.feat1": "Экономика с /sell и /ah",
    "project.gridmc.feat2": "Без /spawn и лишнего мусора",
    "project.gridmc.feat3": "Один мир без правил",
    "project.gridmc.feat4": "Максимально ванильный геймплей",
    "contact.title": "Контакты",
    "contact.subtitle": "Связаться",
    "contact.heading": "Давайте создадим что-то **вместе**",
    "contact.text": "Есть проект или просто хотите пообщаться? Напишите мне в Телеграм - я всегда готов обсудить и реализовать именно ваш проект по отличной цене.",
    "contact.button": "Написать в Телеграм",
    "github.title": "Код",
    "github.subtitle": "GitHub репозитории",
    "footer.rights": "Все права защищены.",
    "notFound.title": "Страница не найдена",
    "notFound.text": "Такой страницы не существует. Возможно, она была перемещена или удалена.",
    "notFound.button": "На главную",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");
  const [isChanging, setIsChanging] = useState(false);
  const [contentOpacity, setContentOpacity] = useState(true);

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language | null;
    if (saved && (saved === "en" || saved === "ru")) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setContentOpacity(false);
    setTimeout(() => {
      setLangState(newLang);
      localStorage.setItem("lang", newLang);
      setTimeout(() => setContentOpacity(true), 100);
    }, 500);
  };

  const t = (key: string): string => {
    const value = translations[lang][key];
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      <div
        className={`transition-opacity duration-500 ${contentOpacity ? "opacity-100" : "opacity-0"}`}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
