"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Language = "en" | "ru" | "lv" | "zh" | "es" | "hi" | "pt" | "fr" | "de" | "ja" | "ko";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.code": "Code",
    "nav.contacts": "Contacts",
    "hero.greeting": "Hi, I'm",
    "hero.name": "KusokMedi",
    "hero.title": "Developer / Programmer",
    "hero.description": "I create websites, bots, automation and digital solutions. Specialization: Python, React, Node.js, Linux.",
    "hero.cta": "What I can do",
    "terminal.line1": "I'm KusokMedi :)",
    "terminal.line2": "Developer ready to turn your idea into code!",
    "terminal.line3": "",
    "terminal.line4": "I can create a Bot, Website or Application for you,",
    "terminal.line5": "help with hosting, improve your current project,",
    "terminal.line6": "integrate AI or other services into your product!",
    "terminal.line7": "",
    "terminal.line8": "Let's create something cool!",
    "about.title": "About Me",
    "about.subtitle": "Who I am",
    "about.heading": "I create digital products that **matter**",
    "about.text1": "I am a developer who doesn't limit myself to one stack. Websites, Telegram bots, APIs, server infrastructure - I understand and do it all. I quickly get into context and start working.",
    "about.text2": "I specialize in Python, React, Node.js and Linux. I take a project from concept to production, working with the full stack. My approach: understand the problem, choose the right tools and build something that works reliably.",
    "highlight.experience": "Experience",
    "highlight.experience.value": "3+ years",
    "highlight.experience.desc": "Commercial development and work on projects of different scales - from startups to large systems",
    "highlight.projects": "Projects",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Completed projects in various fields: from Telegram bots to server infrastructure",
    "highlight.tech": "Technologies",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Programming languages, frameworks and tools I master at a professional level",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits on GitHub during all the time of active open-source and personal projects development",
    "services.title": "Services",
    "services.subtitle": "What I do",
    "services.heading": "What I can do **for you**",
    "services.description": "Full development cycle - from concept to deployment. I work with the entire stack to create a ready-made solution.",
    "service.web.title": "Web Development",
    "service.web.desc": "Websites, web applications and admin panels.",
    "service.web.detail1": "Responsive websites",
    "service.web.detail2": "Web applications",
    "service.web.detail3": "Admin panels",
    "service.web.detail4": "Landing pages",
    "service.bots.title": "Bot Development",
    "service.bots.desc": "Telegram bots, Discord bots and automation.",
    "service.bots.detail1": "Telegram bots",
    "service.bots.detail2": "Discord bots",
    "service.bots.detail3": "Chat automation",
    "service.bots.detail4": "AI integration",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, databases and server logic.",
    "service.backend.detail1": "REST and GraphQL API",
    "service.backend.detail2": "Database design",
    "service.backend.detail3": "Authentication",
    "service.backend.detail4": "Microservices",
    "service.linux.title": "Linux / Servers",
    "service.linux.desc": "Server configuration, optimization and automation.",
    "service.linux.detail1": "Server configuration",
    "service.linux.detail2": "Docker deployment",
    "service.linux.detail3": "CI/CD pipelines",
    "service.linux.detail4": "Monitoring",
    "service.programs.title": "Programs",
    "service.programs.desc": "Utilities, scripts and programs for any tasks.",
    "service.programs.detail1": "CLI tools",
    "service.programs.detail2": "Automation scripts",
    "service.programs.detail3": "Desktop utilities",
    "service.programs.detail4": "Data processing",
    "service.audit.title": "Audit and Consulting",
    "service.audit.desc": "Refactoring, optimization and architectural solutions.",
    "service.audit.detail1": "Code and project audit",
    "service.audit.detail2": "Performance optimization",
    "service.audit.detail3": "System architecture",
    "service.audit.detail4": "Technical documentation",
    "service.hosting.title": "Hosting and Deploy",
    "service.hosting.desc": "Hosting your sites, bots and scripts on the server. Turnkey solutions launch.",
    "service.hosting.detail1": "Ready scripts and bots hosting",
    "service.hosting.detail2": "VPS/VDS and hosting setup",
    "service.hosting.detail3": "Domains and SSL certificates",
    "service.hosting.detail4": "Project migration",
    "service.support.title": "Support and Maintenance",
    "service.support.desc": "Technical support for your projects. Prompt bug fixes and stability control.",
    "service.support.detail1": "Error and bug fixing",
    "service.support.detail2": "Dependencies and systems update",
    "service.support.detail3": "Regular backups setup",
    "service.support.detail4": "24/7 availability monitoring",
    "service.api.title": "API and Services Integration",
    "service.api.desc": "Connecting your sites and programs with external systems for business process automation.",
    "service.api.detail1": "Payment systems connection",
    "service.api.detail2": "CRM integration (amoCRM, Bitrix24)",
    "service.api.detail3": "Messenger notifications setup",
    "service.api.detail4": "Google Sheets synchronization",
    "projects.title": "Projects",
    "projects.subtitle": "My work",
    "projects.heading": "**Featured** works",
    "projects.description": "Real projects created from scratch - each solves specific problems using the right technologies.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot for anonymous messages right in Telegram. Create your link - anyone who follows it will be able to send you an anonymous message.",
    "project.anonspeak.cta": "Open bot",
    "project.anonspeak.feat1": "Create your anonymous link",
    "project.anonspeak.feat2": "Reply to anonymous messages",
    "project.anonspeak.feat3": "Block unwanted users",
    "project.anonspeak.feat4": "Message statistics",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Support bot for Minecraft studio BestDev. Order a plugin, build, consultation or a turnkey solution.",
    "project.bestdev.cta": "Open bot",
    "project.bestdev.feat1": "Order plugins and builds turnkey",
    "project.bestdev.feat2": "Project consultations",
    "project.bestdev.feat3": "Dev team applications",
    "project.bestdev.feat4": "Ready products and solutions",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Vanilla Minecraft server 1.21.11 with economy. /sell, auction, TPA and no extra additions - everything is as vanilla as possible.",
    "project.gridmc.cta": "Join Discord",
    "project.gridmc.feat1": "Economy with /sell and /ah",
    "project.gridmc.feat2": "No /spawn and extra junk",
    "project.gridmc.feat3": "One world without rules",
    "project.gridmc.feat4": "Maximum vanilla gameplay",
    "contact.title": "Contact",
    "contact.subtitle": "Get in touch",
    "contact.heading": "Let's create something **together**",
    "contact.text": "Have a project or just want to chat? Write to me on Telegram - I'm always ready to discuss and implement your project at a great price.",
    "contact.button": "Contact on Telegram",
    "github.title": "Code",
    "github.subtitle": "GitHub repos",
    "footer.rights": "All rights reserved.",
    "notFound.title": "Page not found",
    "notFound.text": "This page does not exist. It may have been moved or deleted.",
    "notFound.button": "Go home",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "Обо мне",
    "nav.services": "Услуги",
    "nav.projects": "Проекты",
    "nav.code": "Код",
    "nav.contacts": "Контакты",
    "hero.greeting": "Привет, я",
    "hero.name": "KusokMedi",
    "hero.title": "Разработчик / Программист",
    "hero.description": "Создаю сайты, ботов, автоматизацию и цифровые решения. Специализация: Python, React, Node.js, Linux.",
    "hero.cta": "Что я умею",
    "terminal.line1": "Я - KusokMedi :)",
    "terminal.line2": "Разработчик, готовый воплотить вашу идею в код!",
    "terminal.line3": "",
    "terminal.line4": "Я могу создать для вас Бота, Сайт или Приложение,",
    "terminal.line5": "помочь с хостингом, улучшить текущий проект,",
    "terminal.line6": "интегрировать ИИ или другие сервисы в ваш продукт!",
    "terminal.line7": "",
    "terminal.line8": "Давайте создадим что-то крутое!",
    "about.title": "Обо мне",
    "about.subtitle": "Кто я",
    "about.heading": "Создаю цифровые продукты, которые **имеют значение**",
    "about.text1": "Я разработчик, который не ограничивается одним стеком. Сайты, Telegram-боты, API, серверная инфраструктура - я разбираюсь и делаю. Быстро вхожу в контекст и приступаю к работе.",
    "about.text2": "Специализируюсь на Python, React, Node.js и Linux. Беру проект от концепции до продакшена, работаю с полным стеком. Мой подход: понять проблему, выбрать правильные инструменты и построить то, что надежно работает.",
    "highlight.experience": "Опыт",
    "highlight.experience.value": "3+ года",
    "highlight.experience.desc": "Коммерческой разработки и работы над проектами разного масштаба - от стартапов до крупных систем",
    "highlight.projects": "Проекты",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Завершённых проектов в самых разных сферах: от Telegram-ботов до серверной инфраструктуры",
    "highlight.tech": "Технологии",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Языков программирования, фреймворков и инструментов, которыми я владею на профессиональном уровне",
    "highlight.commits": "Коммиты",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Коммитов на GitHub за всё время активной разработки open-source и личных проектов",
    "services.title": "Услуги",
    "services.subtitle": "Чем занимаюсь",
    "services.heading": "Что я могу **для вас сделать**",
    "services.description": "Полный цикл разработки - от концепции до деплоя. Работаю со всем стеком, чтобы создать готовое решение.",
    "service.web.title": "Веб-разработка",
    "service.web.desc": "Сайты, веб-приложения и админ-панели.",
    "service.web.detail1": "Адаптивные сайты",
    "service.web.detail2": "Веб-приложения",
    "service.web.detail3": "Админ-панели",
    "service.web.detail4": "Лендинги",
    "service.bots.title": "Разработка ботов",
    "service.bots.desc": "Telegram-боты, Discord-боты и автоматизация.",
    "service.bots.detail1": "Telegram-боты",
    "service.bots.detail2": "Discord-боты",
    "service.bots.detail3": "Автоматизация чатов",
    "service.bots.detail4": "Интеграция AI",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, базы данных и серверная логика.",
    "service.backend.detail1": "REST и GraphQL API",
    "service.backend.detail2": "Проектирование БД",
    "service.backend.detail3": "Аутентификация",
    "service.backend.detail4": "Микросервисы",
    "service.linux.title": "Linux / Серверы",
    "service.linux.desc": "Настройка, оптимизация и автоматизация серверов.",
    "service.linux.detail1": "Конфигурация серверов",
    "service.linux.detail2": "Деплой через Docker",
    "service.linux.detail3": "CI/CD пайплайны",
    "service.linux.detail4": "Мониторинг",
    "service.programs.title": "Программы",
    "service.programs.desc": "Утилиты, скрипты и программы для любых задач.",
    "service.programs.detail1": "CLI-инструменты",
    "service.programs.detail2": "Скрипты автоматизации",
    "service.programs.detail3": "Десктоп-утилиты",
    "service.programs.detail4": "Обработка данных",
    "service.audit.title": "Аудит и Консалтинг",
    "service.audit.desc": "Рефакторинг, оптимизация и архитектурные решения.",
    "service.audit.detail1": "Аудит кода и проектов",
    "service.audit.detail2": "Оптимизация производительности",
    "service.audit.detail3": "Архитектура систем",
    "service.audit.detail4": "Техническая документация",
    "service.hosting.title": "Хостинг и Деплой",
    "service.hosting.desc": "Размещение ваших сайтов, ботов и скриптов на сервере. Запуск готовых решений «под ключ».",
    "service.hosting.detail1": "Размещение готовых скриптов и ботов",
    "service.hosting.detail2": "Настройка VPS / VDS и хостинга",
    "service.hosting.detail3": "Привязка доменов и SSL-сертификатов",
    "service.hosting.detail4": "Перенос проектов на новые сервера",
    "service.support.title": "Поддержка и Обслуживание",
    "service.support.desc": "Техническое сопровождение ваших проектов. Оперативное исправление багов и контроль стабильности.",
    "service.support.detail1": "Исправление ошибок и багов",
    "service.support.detail2": "Обновление зависимостей и систем",
    "service.support.detail3": "Настройка регулярных бэкапов",
    "service.support.detail4": "Мониторинг доступности 24/7",
    "service.api.title": "Интеграция API и Сервисов",
    "service.api.desc": "Связка ваших сайтов и программ с внешними системами для автоматизации бизнес-процессов.",
    "service.api.detail1": "Подключение платежных систем",
    "service.api.detail2": "Интеграция с CRM (amoCRM, Битрикс24)",
    "service.api.detail3": "Настройка уведомлений в мессенджеры",
    "service.api.detail4": "Синхронизация с Google Таблицами",
    "projects.title": "Проекты",
    "projects.subtitle": "Мои работы",
    "projects.heading": "**Избранные** работы",
    "projects.description": "Реальные проекты, созданные с нуля - каждый решает конкретные задачи с помощью правильных технологий.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Бот для анонимных сообщений прямо в Telegram. Создай свою ссылку - любой, кто перейдёт по ней, сможет написать тебе анонимное сообщение.",
    "project.anonspeak.cta": "Открыть бота",
    "project.anonspeak.feat1": "Создание своей анонимной ссылки",
    "project.anonspeak.feat2": "Ответ на анонимные сообщения",
    "project.anonspeak.feat3": "Блокировка нежелательных пользователей",
    "project.anonspeak.feat4": "Статистика сообщений",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Бот поддержки для Minecraft-студии BestDev. Закажи плагин, сборку, консультацию или готовое решение под ключ.",
    "project.bestdev.cta": "Открыть бота",
    "project.bestdev.feat1": "Заказ плагинов и сборок под ключ",
    "project.bestdev.feat2": "Консультации по проектам",
    "project.bestdev.feat3": "Заявки в команду разработки",
    "project.bestdev.feat4": "Готовые товары и решения",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Ванильный Minecraft-сервер 1.21.11 с экономикой. /sell, аукцион, TPA и никаких лишних дополнений - всё максимально как в ванилле.",
    "project.gridmc.cta": "Зайти в Discord",
    "project.gridmc.feat1": "Экономика с /sell и /ah",
    "project.gridmc.feat2": "Без /spawn и лишнего мусора",
    "project.gridmc.feat3": "Один мир без правил",
    "project.gridmc.feat4": "Максимально ванильный геймплей",
    "contact.title": "Контакты",
    "contact.subtitle": "Связаться",
    "contact.heading": "Давайте создадим что-то **вместе**",
    "contact.text": "Есть проект или просто хотите пообщаться? Напишите мне в Телеграм - я всегда готов обсудить и реализовать именно ваш проект по отличной цене.",
    "contact.button": "Написать в Telegram",
    "github.title": "Код",
    "github.subtitle": "GitHub репозитории",
    "footer.rights": "Все права защищены.",
    "notFound.title": "Страница не найдена",
    "notFound.text": "Такой страницы не существует. Возможно, она была перемещена или удалена.",
    "notFound.button": "На главную",
  },
  lv: {
    "nav.home": "Sākums",
    "nav.about": "Par",
    "nav.services": "Pakalpojumi",
    "nav.projects": "Projekti",
    "nav.code": "Kods",
    "nav.contacts": "Kontakti",
    "hero.greeting": "Sveicināts, esmu",
    "hero.name": "KusokMedi",
    "hero.title": "Izstrādātājs / Programmers",
    "hero.description": "Veidoju vietnes, botus, automatizāciju un digitālos risinājumus. Specializācija: Python, React, Node.js, Linux.",
    "hero.cta": "Ko es māku",
    "terminal.line1": "Esmu KusokMedi :)",
    "terminal.line2": "Izstrādātājs, gatavs pārveidot tavu ideju kodā!",
    "terminal.line3": "",
    "terminal.line4": "Varu izveidot Botu, Vietni vai Lietotni tev,",
    "terminal.line5": "palīdzēt ar hostingu, uzlabot esošo projektu,",
    "terminal.line6": "integrēt AI vai citus pakalpojumus tavā produktā!",
    "terminal.line7": "",
    "terminal.line8": "Radīsim ko foršu kopā!",
    "about.title": "Par mani",
    "about.subtitle": "Kas es esmu",
    "about.heading": "Veidoju digitālos produktus, kas **ir svarīgi**",
    "about.text1": "Esmu izstrādātājs, kurš neierobežo sevi ar vienu tehnoloģiju kaudzi. Vietnes, Telegram boti, API, servera infrastruktūra - es saprotu un daru visu. Ātri ienāku kontekstā un sāku strādāt.",
    "about.text2": "Specializējos Python, React, Node.js un Linux. Vadīju projektu no koncepta līdz produkcijai, strādājot ar pilno kaudzi. Mana pieeja: saprast problēmu, izvēlēties pareizos rīkus un uzbūvēt kaut ko, kas droši darbojas.",
    "highlight.experience": "Pieredze",
    "highlight.experience.value": "3+ gadi",
    "highlight.experience.desc": "Komerciāla izstrāde un darbs pie dažāda mēroga projektiem - no startupiem līdz lielām sistēmām",
    "highlight.projects": "Projekti",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Pabeigti projekti dažādās jomās: no Telegram botiem līdz servera infrastruktūrai",
    "highlight.tech": "Tehnoloģijas",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Progammēšanas valodas, ietvari un rīki, kuros esmu profesionālā līmenī",
    "highlight.commits": "Komiti",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Komiti GitHub visas aktīvās atvērtā koda un personīgo projektu izstrādes laikā",
    "services.title": "Pakalpojumi",
    "services.subtitle": "Ko es daru",
    "services.heading": "Ko es varu **jums** izdarīt",
    "services.description": "Pilns izstrādes cikls - no koncepta līdz deployment. Strādāju ar visu kaudzi, lai radītu gatavu risinājumu.",
    "service.web.title": "Web izstrāde",
    "service.web.desc": "Vietnes, web lietotnes un admin panouri.",
    "service.web.detail1": "Responsīvas vietnes",
    "service.web.detail2": "Web lietotnes",
    "service.web.detail3": "Admin panouri",
    "service.web.detail4": "Landing lapas",
    "service.bots.title": "Botu izstrāde",
    "service.bots.desc": "Telegram boti, Discord boti un automatizācija.",
    "service.bots.detail1": "Telegram boti",
    "service.bots.detail2": "Discord boti",
    "service.bots.detail3": "Čata automatizācija",
    "service.bots.detail4": "AI integrācija",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, datubāzes un servera loģika.",
    "service.backend.detail1": "REST un GraphQL API",
    "service.backend.detail2": "Datubāzes dizains",
    "service.backend.detail3": "Autentifikācija",
    "service.backend.detail4": "Mikropakalpojumi",
    "service.linux.title": "Linux / Serveri",
    "service.linux.desc": "Servera konfigurācija, optimizācija un automatizācija.",
    "service.linux.detail1": "Servera konfigurācija",
    "service.linux.detail2": "Docker deployment",
    "service.linux.detail3": "CI/CD pipelines",
    "service.linux.detail4": "Monitoring",
    "service.programs.title": "Programmas",
    "service.programs.desc": "Utilītes, skripti un programmas jebkuriem uzdevumiem.",
    "service.programs.detail1": "CLI rīki",
    "service.programs.detail2": "Automatizācijas skripti",
    "service.programs.detail3": "Desktop utilītes",
    "service.programs.detail4": "Datu apstrāde",
    "service.audit.title": " audits un Konsultācijas",
    "service.audit.desc": "Refaktoring, optimizācija un arhitektūras risinājumi.",
    "service.audit.detail1": "Koda un projektu audits",
    "service.audit.detail2": "Veiktspējas optimizācija",
    "service.audit.detail3": "Sistēmu arhitektūra",
    "service.audit.detail4": "Tehniskā dokumentācija",
    "service.hosting.title": "Hostings un Deploy",
    "service.hosting.desc": "Tavu vietņu, botu un skriptu hostings uz servera. Gatavi risinājumi.",
    "service.hosting.detail1": "Gatu skriptu un botu hostings",
    "service.hosting.detail2": "VPS/VDS un hostinga setup",
    "service.hosting.detail3": "Domēni un SSL sertifikāti",
    "service.hosting.detail4": "Projektu migrācija",
    "service.support.title": "Atbalsts un Uzturēšana",
    "service.support.desc": "Tehniskais atbalsts taviem projektiem. Ātra kļūdu labošana un stabilitātes kontrole.",
    "service.support.detail1": "Kļūdu un bugu labošana",
    "service.support.detail2": "Atkarību un sistēmu atjaunināšana",
    "service.support.detail3": "Regulāru backupu iestatīšana",
    "service.support.detail4": "24/7 pieejamības monitoring",
    "service.api.title": "API un Pakalpojumu Integrācija",
    "service.api.desc": "Tavu vietņu un programmu savienošana ar ārējām sistēmām biznesa procesu automatizācijai.",
    "service.api.detail1": "Maksājumu sistēmu pieslēgšana",
    "service.api.detail2": "CRM integrācija (amoCRM, Bitrix24)",
    "service.api.detail3": "Ziņojumu paziņojumu iestatīšana",
    "service.api.detail4": "Google Sheets sinhronizācija",
    "projects.title": "Projekti",
    "projects.subtitle": "Mans darbs",
    "projects.heading": "**Atlasītie** darbi",
    "projects.description": "Reāli projekti, radīti no nulles - katrs risina konkrētas problēmas, izmantojot pareizās tehnoloģijas.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bots anonīmiem ziņojumiem Telegram. Izveido savu linku - ikviens, kas to atvērs, varēs tev nosūtīt anonīmu ziņojumu.",
    "project.anonspeak.cta": "Atvērt botu",
    "project.anonspeak.feat1": "Izveido savu anonīmo linku",
    "project.anonspeak.feat2": "Atbildi uz anonīmiem ziņojumiem",
    "project.anonspeak.feat3": "Bloķē nevēlamos lietotājus",
    "project.anonspeak.feat4": "Ziņojumu statistika",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Atbalsta bots Minecraft studijai BestDev. Pasūti spraudni, build, konsultāciju vai gatavu risinājumu.",
    "project.bestdev.cta": "Atvērt botu",
    "project.bestdev.feat1": "Pasūti spraudņus un buildus gatavus",
    "project.bestdev.feat2": "Projektu konsultācijas",
    "project.bestdev.feat3": "Pieslēgšanās izstrādes komandai",
    "project.bestdev.feat4": "Gatavi produkti un risinājumi",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Vanilla Minecraft serveris 1.21.11 ar ekonomiku. /sell, auction, TPA un bez liekām ekstrām - viss pēc iespējas vanilla.",
    "project.gridmc.cta": "Pievienoties Discord",
    "project.gridmc.feat1": "Ekonomika ar /sell un /ah",
    "project.gridmc.feat2": "Bez /spawn un liekiem čakarjiem",
    "project.gridmc.feat3": "Viena pasaule bez noteikumiem",
    "project.gridmc.feat4": "Maksimāli vanilla gameplay",
    "contact.title": "Kontakti",
    "contact.subtitle": "Sazinies",
    "contact.heading": "Radīsim ko **kopā**",
    "contact.text": "Ir projekts vai vienkārši gribi parunāt? Uzraksti man uz Telegram - vienmēr esmu gatavs apspriest un realizēt tavu projektu par lielisku cenu.",
    "contact.button": "Rakstīt Telegramā",
    "github.title": "Kods",
    "github.subtitle": "GitHub repozitoriji",
    "footer.rights": "Visas tiesības aizsargātas.",
    "notFound.title": "Lapa nav atrasta",
    "notFound.text": "Šāda lapas neeksistē. Iespējams, tā ir pārvietota vai izdzēsta.",
    "notFound.button": "Uz sākumu",
  },
  zh: {
    "nav.home": "首页",
    "nav.about": "关于",
    "nav.services": "服务",
    "nav.projects": "项目",
    "nav.code": "代码",
    "nav.contacts": "联系",
    "hero.greeting": "你好，我是",
    "hero.name": "KusokMedi",
    "hero.title": "开发者 / 程序员",
    "hero.description": "我创建网站、机器人、自动化和数字解决方案。专长：Python、React、Node.js、Linux。",
    "hero.cta": "我能做什么",
    "terminal.line1": "我是 KusokMedi :)",
    "terminal.line2": "开发者，准备将你的想法变成代码！",
    "terminal.line3": "",
    "terminal.line4": "我可以为你创建机器人、网站或应用程序，",
    "terminal.line5": "帮助托管、改进你的现有项目，",
    "terminal.line6": "将AI或其他服务集成到你的产品中！",
    "terminal.line7": "",
    "terminal.line8": "让我们一起创造一些酷的东西！",
    "about.title": "关于我",
    "about.subtitle": "我是谁",
    "about.heading": "我创造的数字产品**很重要**",
    "about.text1": "我是一名不局限于单一技术栈的开发者。网站、Telegram机器人、API、服务器基础设施——我都能理解和实现。我快速进入状态并开始工作。",
    "about.text2": "我专精于Python、React、Node.js和Linux。我从概念到生产全程负责项目，使用全栈方式工作。我的方法是：理解问题，选择正确的工具，构建可靠运行的东西。",
    "highlight.experience": "经验",
    "highlight.experience.value": "3+ 年",
    "highlight.experience.desc": "商业开发和不同规模项目的工作经验——从初创公司到大型系统",
    "highlight.projects": "项目",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "在各个领域完成的项目：从Telegram机器人到服务器基础设施",
    "highlight.tech": "技术",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "我专业掌握的编程语言、框架和工具",
    "highlight.commits": "提交",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "在GitHub上活跃开发开源和个人项目期间的所有提交",
    "services.title": "服务",
    "services.subtitle": "我的工作",
    "services.heading": "我能**为你**做什么",
    "services.description": "完整的开发周期——从概念到部署。我使用整个技术栈来创建现成的解决方案。",
    "service.web.title": "Web开发",
    "service.web.desc": "网站、Web应用程序和管理面板。",
    "service.web.detail1": "响应式网站",
    "service.web.detail2": "Web应用程序",
    "service.web.detail3": "管理面板",
    "service.web.detail4": "落地页",
    "service.bots.title": "机器人开发",
    "service.bots.desc": "Telegram机器人、Discord机器人和自动化。",
    "service.bots.detail1": "Telegram机器人",
    "service.bots.detail2": "Discord机器人",
    "service.bots.detail3": "聊天自动化",
    "service.bots.detail4": "AI集成",
    "service.backend.title": "后端",
    "service.backend.desc": "API、数据库和服务器逻辑。",
    "service.backend.detail1": "REST和GraphQL API",
    "service.backend.detail2": "数据库设计",
    "service.backend.detail3": "身份验证",
    "service.backend.detail4": "微服务",
    "service.linux.title": "Linux / 服务器",
    "service.linux.desc": "服务器配置、优化和自动化。",
    "service.linux.detail1": "服务器配置",
    "service.linux.detail2": "Docker部署",
    "service.linux.detail3": "CI/CD流水线",
    "service.linux.detail4": "监控",
    "service.programs.title": "程序",
    "service.programs.desc": "用于任何任务的实用程序、脚本和程序。",
    "service.programs.detail1": "CLI工具",
    "service.programs.detail2": "自动化脚本",
    "service.programs.detail3": "桌面实用程序",
    "service.programs.detail4": "数据处理",
    "service.audit.title": "审计和咨询",
    "service.audit.desc": "重构、优化和架构解决方案。",
    "service.audit.detail1": "代码和项目审计",
    "service.audit.detail2": "性能优化",
    "service.audit.detail3": "系统架构",
    "service.audit.detail4": "技术文档",
    "service.hosting.title": "托管和部署",
    "service.hosting.desc": "在服务器上托管你的网站、机器人和脚本。一站式解决方案启动。",
    "service.hosting.detail1": "现成脚本和机器人托管",
    "service.hosting.detail2": "VPS/VDS和托管设置",
    "service.hosting.detail3": "域名和SSL证书",
    "service.hosting.detail4": "项目迁移",
    "service.support.title": "支持和维护",
    "service.support.desc": "项目的技术支持。快速修复bug和控制稳定性。",
    "service.support.detail1": "错误和bug修复",
    "service.support.detail2": "依赖项和系统更新",
    "service.support.detail3": "定期备份设置",
    "service.support.detail4": "24/7可用性监控",
    "service.api.title": "API和服务集成",
    "service.api.desc": "将你的网站和程序与外部系统连接，实现业务流程自动化。",
    "service.api.detail1": "支付系统连接",
    "service.api.detail2": "CRM集成 (amoCRM, Bitrix24)",
    "service.api.detail3": "消息通知设置",
    "service.api.detail4": "Google表格同步",
    "projects.title": "项目",
    "projects.subtitle": "我的作品",
    "projects.heading": "**精选**作品",
    "projects.description": "从头创建的真实项目——每个项目都使用正确的技术解决具体问题。",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Telegram中的匿名消息机器人。创建你的链接——任何人都可以通过它向你发送匿名消息。",
    "project.anonspeak.cta": "打开机器人",
    "project.anonspeak.feat1": "创建你的匿名链接",
    "project.anonspeak.feat2": "回复匿名消息",
    "project.anonspeak.feat3": "阻止不需要的用户",
    "project.anonspeak.feat4": "消息统计",
    "project.bestdev.title": "BestDev支持机器人",
    "project.bestdev.desc": "Minecraft工作室BestDev的支持机器人。订购插件、构建、咨询或一站式解决方案。",
    "project.bestdev.cta": "打开机器人",
    "project.bestdev.feat1": "一站式订购插件和构建",
    "project.bestdev.feat2": "项目咨询",
    "project.bestdev.feat3": "开发团队申请",
    "project.bestdev.feat4": "现成的产品和解决方案",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "带有经济系统的香草Minecraft服务器1.21.11。/sell、拍卖、TPA，没有任何额外添加——尽可能保持香草。",
    "project.gridmc.cta": "加入Discord",
    "project.gridmc.feat1": "经济系统与/sell和/ah",
    "project.gridmc.feat2": "没有/spawn和额外垃圾",
    "project.gridmc.feat3": "一个没有规则的世界",
    "project.gridmc.feat4": "最大化的香草游戏体验",
    "contact.title": "联系",
    "contact.subtitle": "联系我们",
    "contact.heading": "让我们一起**创造**一些东西",
    "contact.text": "有项目还是只是想聊聊？在Telegram上给我写消息——我总是准备好以很好的价格讨论和实现你的项目。",
    "contact.button": "写Telegram",
    "github.title": "代码",
    "github.subtitle": "GitHub仓库",
    "footer.rights": "版权所有。",
    "notFound.title": "页面未找到",
    "notFound.text": "此页面不存在。可能已被移动或删除。",
    "notFound.button": "回家",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Sobre mí",
    "nav.services": "Servicios",
    "nav.projects": "Proyectos",
    "nav.code": "Código",
    "nav.contacts": "Contactos",
    "hero.greeting": "Hola, soy",
    "hero.name": "KusokMedi",
    "hero.title": "Desarrollador / Programador",
    "hero.description": "Creo sitios web, bots, automatización y soluciones digitales. Especialización: Python, React, Node.js, Linux.",
    "hero.cta": "Lo que puedo hacer",
    "terminal.line1": "Soy KusokMedi :)",
    "terminal.line2": "¡Desarrollador listo para convertir tu idea en código!",
    "terminal.line3": "",
    "terminal.line4": "Puedo crear un Bot, Sitio Web o Aplicación para ti,",
    "terminal.line5": "ayudar con el hosting, mejorar tu proyecto actual,",
    "terminal.line6": "¡integrar IA u otros servicios en tu producto!",
    "terminal.line7": "",
    "terminal.line8": "¡Creemos algo genial juntos!",
    "about.title": "Sobre mí",
    "about.subtitle": "Quién soy",
    "about.heading": "Creo productos digitales que **importan**",
    "about.text1": "Soy un desarrollador que no se limita a una sola tecnología. Sitios web, bots de Telegram, APIs, infraestructura de servidores - entiendo y hago de todo. Me adapto rápidamente al contexto y comienzo a trabajar.",
    "about.text2": "Me especializo en Python, React, Node.js y Linux. Llevo un proyecto desde el concepto hasta la producción, trabajando con toda la pila tecnológica. Mi enfoque: entender el problema, elegir las herramientas correctas y construir algo que funcione de manera confiable.",
    "highlight.experience": "Experiencia",
    "highlight.experience.value": "3+ años",
    "highlight.experience.desc": "Desarrollo comercial y trabajo en proyectos de diferentes escalas - desde startups hasta sistemas grandes",
    "highlight.projects": "Proyectos",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Proyectos completados en varios campos: desde bots de Telegram hasta infraestructura de servidores",
    "highlight.tech": "Tecnologías",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Lenguajes de programación, frameworks y herramientas que domino a nivel profesional",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits en GitHub durante todo el tiempo de desarrollo activo de proyectos de código abierto y personales",
    "services.title": "Servicios",
    "services.subtitle": "Qué hago",
    "services.heading": "Lo que puedo hacer **por ti**",
    "services.description": "Ciclo de desarrollo completo - desde el concepto hasta el despliegue. Trabajo con toda la pila para crear una solución lista para usar.",
    "service.web.title": "Desarrollo Web",
    "service.web.desc": "Sitios web, aplicaciones web y paneles de administración.",
    "service.web.detail1": "Sitios web responsivos",
    "service.web.detail2": "Aplicaciones web",
    "service.web.detail3": "Paneles de administración",
    "service.web.detail4": "Landing pages",
    "service.bots.title": "Desarrollo de Bots",
    "service.bots.desc": "Bots de Telegram, bots de Discord y automatización.",
    "service.bots.detail1": "Bots de Telegram",
    "service.bots.detail2": "Bots de Discord",
    "service.bots.detail3": "Automatización de chat",
    "service.bots.detail4": "Integración de IA",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, bases de datos y lógica del servidor.",
    "service.backend.detail1": "API REST y GraphQL",
    "service.backend.detail2": "Diseño de base de datos",
    "service.backend.detail3": "Autenticación",
    "service.backend.detail4": "Microservicios",
    "service.linux.title": "Linux / Servidores",
    "service.linux.desc": "Configuración, optimización y automatización de servidores.",
    "service.linux.detail1": "Configuración de servidores",
    "service.linux.detail2": "Despliegue con Docker",
    "service.linux.detail3": "Pipelines CI/CD",
    "service.linux.detail4": "Monitoreo",
    "service.programs.title": "Programas",
    "service.programs.desc": "Utilidades, scripts y programas para cualquier tarea.",
    "service.programs.detail1": "Herramientas CLI",
    "service.programs.detail2": "Scripts de automatización",
    "service.programs.detail3": "Utilidades de escritorio",
    "service.programs.detail4": "Procesamiento de datos",
    "service.audit.title": "Auditoría y Consultoría",
    "service.audit.desc": "Refactorización, optimización y soluciones arquitectónicas.",
    "service.audit.detail1": "Auditoría de código y proyectos",
    "service.audit.detail2": "Optimización del rendimiento",
    "service.audit.detail3": "Arquitectura de sistemas",
    "service.audit.detail4": "Documentación técnica",
    "service.hosting.title": "Hosting y Despliegue",
    "service.hosting.desc": "Alojamiento de tus sitios, bots y scripts en el servidor. Soluciones llave en mano.",
    "service.hosting.detail1": "Alojamiento de scripts y bots listos",
    "service.hosting.detail2": "Configuración de VPS/VDS y hosting",
    "service.hosting.detail3": "Dominios y certificados SSL",
    "service.hosting.detail4": "Migración de proyectos",
    "service.support.title": "Soporte y Mantenimiento",
    "service.support.desc": "Soporte técnico para tus proyectos. Corrección rápida de errores y control de estabilidad.",
    "service.support.detail1": "Corrección de errores",
    "service.support.detail2": "Actualización de dependencias y sistemas",
    "service.support.detail3": "Configuración de backups regulares",
    "service.support.detail4": "Monitoreo de disponibilidad 24/7",
    "service.api.title": "Integración de API y Servicios",
    "service.api.desc": "Conectar tus sitios y programas con sistemas externos para la automatización de procesos de negocio.",
    "service.api.detail1": "Conexión de sistemas de pago",
    "service.api.detail2": "Integración con CRM (amoCRM, Bitrix24)",
    "service.api.detail3": "Configuración de notificaciones en mensajeros",
    "service.api.detail4": "Sincronización con Google Sheets",
    "projects.title": "Proyectos",
    "projects.subtitle": "Mi trabajo",
    "projects.heading": "Trabajos **destacados**",
    "projects.description": "Proyectos reales creados desde cero - cada uno resuelve problemas específicos usando las tecnologías correctas.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot para mensajes anónimos en Telegram. Crea tu enlace - cualquiera que lo siga podrá enviarte un mensaje anónimo.",
    "project.anonspeak.cta": "Abrir bot",
    "project.anonspeak.feat1": "Crea tu enlace anónimo",
    "project.anonspeak.feat2": "Responde mensajes anónimos",
    "project.anonspeak.feat3": "Bloquea usuarios no deseados",
    "project.anonspeak.feat4": "Estadísticas de mensajes",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Bot de soporte para el estudio de Minecraft BestDev. Solicita un plugin, build, consultoría o una solución llave en mano.",
    "project.bestdev.cta": "Abrir bot",
    "project.bestdev.feat1": "Solicita plugins y builds llave en mano",
    "project.bestdev.feat2": "Consultorías de proyectos",
    "project.bestdev.feat3": "Solicitudes al equipo de desarrollo",
    "project.bestdev.feat4": "Productos y soluciones listos",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Servidor de Minecraft vanilla 1.21.11 con economía. /sell, auction, TPA y sin adiciones extra - todo lo más vanilla posible.",
    "project.gridmc.cta": "Unirse a Discord",
    "project.gridmc.feat1": "Economía con /sell y /ah",
    "project.gridmc.feat2": "Sin /spawn y basura extra",
    "project.gridmc.feat3": "Un mundo sin reglas",
    "project.gridmc.feat4": "Gameplay vanilla máximo",
    "contact.title": "Contacto",
    "contact.subtitle": "Ponerse en contacto",
    "contact.heading": "Creemos algo **juntos**",
    "contact.text": "¿Tienes un proyecto o simplemente quieres charlar? Escríbeme a Telegram - siempre estoy listo para discutir e implementar tu proyecto a un gran precio.",
    "contact.button": "Escribir a Telegram",
    "github.title": "Código",
    "github.subtitle": "Repositorios de GitHub",
    "footer.rights": "Todos los derechos reservados.",
    "notFound.title": "Página no encontrada",
    "notFound.text": "Esta página no existe. Puede haber sido movida o eliminada.",
    "notFound.button": "Ir a inicio",
  },
  hi: {
    "nav.home": "होम",
    "nav.about": "के बारे में",
    "nav.services": "सेवाएं",
    "nav.projects": "प्रोजेक्ट्स",
    "nav.code": "कोड",
    "nav.contacts": "संपर्क",
    "hero.greeting": "नमस्ते, मैं हूं",
    "hero.name": "KusokMedi",
    "hero.title": "डेवलपर / प्रोग्रामर",
    "hero.description": "मैं वेबसाइट, बॉट, ऑटोमेशन और डिजिटल समाधान बनाता हूं। विशेषज्ञता: Python, React, Node.js, Linux।",
    "hero.cta": "मैं क्या कर सकता हूं",
    "terminal.line1": "मैं KusokMedi हूं :)",
    "terminal.line2": "डेवलपर जो आपके विचार को कोड में बदलने के लिए तैयार है!",
    "terminal.line3": "",
    "terminal.line4": "मैं आपके लिए बॉट, वेबसाइट या ऐप बना सकता हूं,",
    "terminal.line5": "होस्टिंग में मदद कर सकता हूं, आपके मौजूदा प्रोजेक्ट को बेहतर बना सकता हूं,",
    "terminal.line6": "AI या अन्य सेवाओं को आपके उत्पाद में शामिल कर सकता हूं!",
    "terminal.line7": "",
    "terminal.line8": "चलो कुछ कूल बनाते हैं!",
    "about.title": "मेरे बारे में",
    "about.subtitle": "मैं कौन हूं",
    "about.heading": "मैं डिजिटल उत्पाद बनाता हूं जो **मायने रखते हैं**",
    "about.text1": "मैं एक डेवलपर हूं जो खुद को एक ही स्टैक तक सीमित नहीं रखता। वेबसाइट, Telegram बॉट, API, सर्वर इन्फ्रास्ट्रक्चर - मैं समझता हूं और करता हूं सब कुछ। मैं जल्दी से संदर्भ में आता हूं और काम शुरू कर देता हूं।",
    "about.text2": "मेरी विशेषज्ञता Python, React, Node.js और Linux में है। मैं कॉन्सेप्ट से लेकर प्रोडक्शन तक प्रोजेक्ट लेता हूं, फुल स्टैक के साथ काम करता हूं। मेरा दृष्टिकोण: समस्या को समझो, सही टूल्स चुनो और कुछ बनाओ जो विश्वसनीय रूप से काम करे।",
    "highlight.experience": "अनुभव",
    "highlight.experience.value": "3+ साल",
    "highlight.experience.desc": "कमर्शियल डेवलपमेंट और विभिन्न पैमाने की प्रोजेक्ट्स पर काम - स्टार्टअप से लेकर बड़े सिस्टम तक",
    "highlight.projects": "प्रोजेक्ट्स",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "विभिन्न क्षेत्रों में पूर्ण प्रोजेक्ट्स: Telegram बॉट से लेकर सर्वर इन्फ्रास्ट्रक्चर तक",
    "highlight.tech": "टेक्नोलॉजीज",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "प्रोग्रामिंग भाषाएं, फ्रेमवर्क और टूल्स जिनमें मैं पेशेवर स्तर पर महारत हूं",
    "highlight.commits": "कमिट्स",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "GitHub पर सक्रिय ओपन-सोर्स और व्यक्तिगत प्रोजेक्ट्स डेवलपमेंट के दौरान सभी कमिट्स",
    "services.title": "सेवाएं",
    "services.subtitle": "मैं क्या करता हूं",
    "services.heading": "मैं **आपके लिए** क्या कर सकता हूं",
    "services.description": "पूर्ण डेवलपमेंट साइकिल - कॉन्सेप्ट से लेकर डिप्लॉयमेंट तक। मैं रेडी-टू-यूज सॉल्यूशन बनाने के लिए पूरे स्टैक के साथ काम करता हूं।",
    "service.web.title": "वेब डेवलपमेंट",
    "service.web.desc": "वेबसाइट, वेब ऐप्स और एडमिन पैनल।",
    "service.web.detail1": "रिस्पॉन्सिव वेबसाइट्स",
    "service.web.detail2": "वेब ऐप्लिकेशन",
    "service.web.detail3": "एडमिन पैनल",
    "service.web.detail4": "लैंडिंग पेज",
    "service.bots.title": "बॉट डेवलपमेंट",
    "service.bots.desc": "Telegram बॉट, Discord बॉट और ऑटोमेशन।",
    "service.bots.detail1": "Telegram बॉट",
    "service.bots.detail2": "Discord बॉट",
    "service.bots.detail3": "चैट ऑटोमेशन",
    "service.bots.detail4": "AI इंटीग्रेशन",
    "service.backend.title": "बैकेंड",
    "service.backend.desc": "API, डेटाबेस और सर्वर लॉजिक।",
    "service.backend.detail1": "REST और GraphQL API",
    "service.backend.detail2": "डेटाबेस डिज़ाइन",
    "service.backend.detail3": "ऑथेंटिकेशन",
    "service.backend.detail4": "माइक्रोसर्विसेज",
    "service.linux.title": "Linux / सर्वर",
    "service.linux.desc": "सर्वर कॉन्फ़िगरेशन, ऑप्टिमाइज़ेशन और ऑटोमेशन।",
    "service.linux.detail1": "सर्वर कॉन्फ़िगरेशन",
    "service.linux.detail2": "Docker डिप्लॉयमेंट",
    "service.linux.detail3": "CI/CD पाइपलाइन",
    "service.linux.detail4": "मॉनिटरिंग",
    "service.programs.title": "प्रोग्राम्स",
    "service.programs.desc": "किसी भी काम के लिए यूटिलिटीज, स्क्रिप्ट और प्रोग्राम।",
    "service.programs.detail1": "CLI टूल्स",
    "service.programs.detail2": "ऑटोमेशन स्क्रिप्ट",
    "service.programs.detail3": "डेस्कटॉप यूटिलिटीज",
    "service.programs.detail4": "डेटा प्रोसेसिंग",
    "service.audit.title": "ऑडिट और कंसल्टिंग",
    "service.audit.desc": "रिफैक्टरिंग, ऑप्टिमाइज़ेशन और आर्किटेक्चरल सॉल्यूशन।",
    "service.audit.detail1": "कोड और प्रोजेक्ट ऑडिट",
    "service.audit.detail2": "परफॉर्मेंस ऑप्टिमाइज़ेशन",
    "service.audit.detail3": "सिस्टम आर्किटेक्चर",
    "service.audit.detail4": "टेक्निकल डॉक्यूमेंटेशन",
    "service.hosting.title": "होस्टिंग और डिप्लॉय",
    "service.hosting.desc": "सर्वर पर आपकी साइट, बॉट और स्क्रिप्ट होस्ट करना। टर्नकी सॉल्यूशन लॉन्च।",
    "service.hosting.detail1": "रेंट-टू-यूज स्क्रिप्ट और बॉट होस्टिंग",
    "service.hosting.detail2": "VPS/VDS और होस्टिंग सेटअप",
    "service.hosting.detail3": "डोमेन और SSL सर्टिफिकेट",
    "service.hosting.detail4": "प्रोजेक्ट माइग्रेशन",
    "service.support.title": "सपोर्ट और मेंटेनेंस",
    "service.support.desc": "आपकी प्रोजेक्ट्स के लिए टेक्निकल सपोर्ट। त्वरित बग फिक्स और स्थिरता नियंत्रण।",
    "service.support.detail1": "एरर और बग फिक्सिंग",
    "service.support.detail2": "डिपेंडेंसी और सिस्टम अपडेट",
    "service.support.detail3": "रेगुलर बैकअप सेटअप",
    "service.support.detail4": "24/7 उपलब्धता मॉनिटरिंग",
    "service.api.title": "API और सर्विसेज इंटीग्रेशन",
    "service.api.desc": "बिज़नेस प्रोसेस ऑटोमेशन के लिए आपकी साइट और प्रोग्राम को बाहरी सिस्टम से जोड़ना।",
    "service.api.detail1": "पेमेंट सिस्टम कनेक्शन",
    "service.api.detail2": "CRM इंटीग्रेशन (amoCRM, Bitrix24)",
    "service.api.detail3": "मेसेंजर नोटिफिकेशन सेटअप",
    "service.api.detail4": "Google Sheets सिंक्रोनाइज़ेशन",
    "projects.title": "प्रोजेक्ट्स",
    "projects.subtitle": "मेरा काम",
    "projects.heading": "**फीचर्ड** काम",
    "projects.description": "शुरू से बनाए गए असली प्रोजेक्ट्स - हर एक सही टेक्नोलॉजी का उपयोग करके विशिष्ट समस्याओं को हल करता है।",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Telegram में एनोनिमस मैसेज के लिए बॉट। अपना लिंक बनाओ - कोई भी जो इसे फॉलो करेगा आपको एनोनिमस मैसेज भेज सकेगा।",
    "project.anonspeak.cta": "बॉट खोलें",
    "project.anonspeak.feat1": "अपना एनोनिमस लिंक बनाएं",
    "project.anonspeak.feat2": "एनोनिमस मैसेज का जवाब दें",
    "project.anonspeak.feat3": "अवांछित यूजर्स को ब्लॉक करें",
    "project.anonspeak.feat4": "मैसेज स्टैटिस्टिक्स",
    "project.bestdev.title": "BestDev सपोर्ट बॉट",
    "project.bestdev.desc": "Minecraft स्टूडियो BestDev के लिए सपोर्ट बॉट। प्लगइन, बिल्ड, कंसल्टेंसी या टर्नकी सॉल्यूशन ऑर्डर करें।",
    "project.bestdev.cta": "बॉट खोलें",
    "project.bestdev.feat1": "टर्नकी प्लगइन और बिल्ड ऑर्डर करें",
    "project.bestdev.feat2": "प्रोजेक्ट कंसल्टेंसी",
    "project.bestdev.feat3": "डेव टीम एप्लिकेशन",
    "project.bestdev.feat4": "रेडी प्रोडक्ट्स और सॉल्यूशन",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "इकोनॉमी के साथ वैनिला Minecraft सर्वर 1.21.11। /sell, auction, TPA और कोई एक्स्ट्रा ऐडिशन नहीं - सब कुछ जितना हो सके वैनिला।",
    "project.gridmc.cta": "Discord में शामिल हों",
    "project.gridmc.feat1": "/sell और /ah के साथ इकोनॉमी",
    "project.gridmc.feat2": "बिना /spawn और एक्स्ट्रा जंक",
    "project.gridmc.feat3": "नियमों के बिना एक दुनिया",
    "project.gridmc.feat4": "अधिकतम वैनिला गेमप्ले",
    "contact.title": "संपर्क",
    "contact.subtitle": "संपर्क करें",
    "contact.heading": "चलो कुछ **साथ मिलकर** बनाएं",
    "contact.text": "प्रोजेक्ट है या बस चैट करना है? Telegram पर मुझे लिखें - मैं हमेशा बेहतरीन कीमत पर आपका प्रोजेक्ट discuss करने और लागू करने के लिए तैयार हूं।",
    "contact.button": "Telegram पर लिखें",
    "github.title": "कोड",
    "github.subtitle": "GitHub रिपॉजिटरीज",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "notFound.title": "पेज नहीं मिला",
    "notFound.text": "यह पेज मौजूद नहीं है। इसे शायद हटा दिया गया या स्थानांतरित कर दिया गया।",
    "notFound.button": "होम पर जाएं",
  },
  pt: {
    "nav.home": "Início",
    "nav.about": "Sobre",
    "nav.services": "Serviços",
    "nav.projects": "Projetos",
    "nav.code": "Código",
    "nav.contacts": "Contatos",
    "hero.greeting": "Olá, eu sou",
    "hero.name": "KusokMedi",
    "hero.title": "Desenvolvedor / Programador",
    "hero.description": "Crio sites, bots, automação e soluções digitais. Especialização: Python, React, Node.js, Linux.",
    "hero.cta": "O que posso fazer",
    "terminal.line1": "Eu sou KusokMedi :)",
    "terminal.line2": "Desenvolvedor pronto para transformar sua ideia em código!",
    "terminal.line3": "",
    "terminal.line4": "Posso criar um Bot, Site ou Aplicativo para você,",
    "terminal.line5": "ajudar com hospedagem, melhorar seu projeto atual,",
    "terminal.line6": "integrar IA ou outros serviços ao seu produto!",
    "terminal.line7": "",
    "terminal.line8": "Vamos criar algo legal juntos!",
    "about.title": "Sobre mim",
    "about.subtitle": "Quem eu sou",
    "about.heading": "Crio produtos digitais que **importam**",
    "about.text1": "Sou um desenvolvedor que não se limita a uma única stack. Sites, bots do Telegram, APIs, infraestrutura de servidores - entendo e faço tudo. Entro rapidamente no contexto e começo a trabalhar.",
    "about.text2": "Especializo-me em Python, React, Node.js e Linux. Levo um projeto do conceito à produção, trabalhando com a stack completa. Minha abordagem: entender o problema, escolher as ferramentas certas e construir algo que funcione de forma confiável.",
    "highlight.experience": "Experiência",
    "highlight.experience.value": "3+ anos",
    "highlight.experience.desc": "Desenvolvimento comercial e trabalho em projetos de diferentes escalas - de startups a sistemas grandes",
    "highlight.projects": "Projetos",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Projetos concluídos em várias áreas: de bots do Telegram a infraestrutura de servidores",
    "highlight.tech": "Tecnologias",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Linguagens de programação, frameworks e ferramentas que domino em nível profissional",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits no GitHub durante todo o tempo de desenvolvimento ativo de projetos open-source e pessoais",
    "services.title": "Serviços",
    "services.subtitle": "O que faço",
    "services.heading": "O que posso fazer **por você**",
    "services.description": "Ciclo completo de desenvolvimento - do conceito à implantação. Trabalho com toda a stack para criar uma solução pronta.",
    "service.web.title": "Desenvolvimento Web",
    "service.web.desc": "Sites, aplicações web e painéis de administração.",
    "service.web.detail1": "Sites responsivos",
    "service.web.detail2": "Aplicações web",
    "service.web.detail3": "Painéis de administração",
    "service.web.detail4": "Landing pages",
    "service.bots.title": "Desenvolvimento de Bots",
    "service.bots.desc": "Bots do Telegram, bots do Discord e automação.",
    "service.bots.detail1": "Bots do Telegram",
    "service.bots.detail2": "Bots do Discord",
    "service.bots.detail3": "Automação de chat",
    "service.bots.detail4": "Integração com IA",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, bancos de dados e lógica do servidor.",
    "service.backend.detail1": "API REST e GraphQL",
    "service.backend.detail2": "Design de banco de dados",
    "service.backend.detail3": "Autenticação",
    "service.backend.detail4": "Microserviços",
    "service.linux.title": "Linux / Servidores",
    "service.linux.desc": "Configuração, otimização e automação de servidores.",
    "service.linux.detail1": "Configuração de servidores",
    "service.linux.detail2": "Implantação com Docker",
    "service.linux.detail3": "Pipelines CI/CD",
    "service.linux.detail4": "Monitoramento",
    "service.programs.title": "Programas",
    "service.programs.desc": "Utilitários, scripts e programas para qualquer tarefa.",
    "service.programs.detail1": "Ferramentas CLI",
    "service.programs.detail2": "Scripts de automação",
    "service.programs.detail3": "Utilitários de desktop",
    "service.programs.detail4": "Processamento de dados",
    "service.audit.title": "Auditoria e Consultoria",
    "service.audit.desc": "Refatoração, otimização e soluções arquiteturais.",
    "service.audit.detail1": "Auditoria de código e projetos",
    "service.audit.detail2": "Otimização de performance",
    "service.audit.detail3": "Arquitetura de sistemas",
    "service.audit.detail4": "Documentação técnica",
    "service.hosting.title": "Hospedagem e Deploy",
    "service.hosting.desc": "Hospedagem dos seus sites, bots e scripts no servidor. Soluções completas.",
    "service.hosting.detail1": "Hospedagem de scripts e bots prontos",
    "service.hosting.detail2": "Configuração de VPS/VDS e hospedagem",
    "service.hosting.detail3": "Domínios e certificados SSL",
    "service.hosting.detail4": "Migração de projetos",
    "service.support.title": "Suporte e Manutenção",
    "service.support.desc": "Suporte técnico para seus projetos. Correção rápida de bugs e controle de estabilidade.",
    "service.support.detail1": "Correção de erros e bugs",
    "service.support.detail2": "Atualização de dependências e sistemas",
    "service.support.detail3": "Configuração de backups regulares",
    "service.support.detail4": "Monitoramento de disponibilidade 24/7",
    "service.api.title": "Integração de API e Serviços",
    "service.api.desc": "Conectar seus sites e programas com sistemas externos para automação de processos de negócio.",
    "service.api.detail1": "Conexão de sistemas de pagamento",
    "service.api.detail2": "Integração com CRM (amoCRM, Bitrix24)",
    "service.api.detail3": "Configuração de notificações em mensageiros",
    "service.api.detail4": "Sincronização com Google Sheets",
    "projects.title": "Projetos",
    "projects.subtitle": "Meu trabalho",
    "projects.heading": "Trabalhos **destacados**",
    "projects.description": "Projetos reais criados do zero - cada um resolve problemas específicos usando as tecnologias certas.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot para mensagens anônimas no Telegram. Crie seu link - qualquer pessoa que seguir poderá enviar mensagens anônimas.",
    "project.anonspeak.cta": "Abrir bot",
    "project.anonspeak.feat1": "Crie seu link anônimo",
    "project.anonspeak.feat2": "Responda mensagens anônimas",
    "project.anonspeak.feat3": "Bloqueie usuários indesejados",
    "project.anonspeak.feat4": "Estatísticas de mensagens",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Bot de suporte para estúdio Minecraft BestDev. Solicite plugins, builds, consultoria ou solução completa.",
    "project.bestdev.cta": "Abrir bot",
    "project.bestdev.feat1": "Solicite plugins e builds completos",
    "project.bestdev.feat2": "Consultorias de projetos",
    "project.bestdev.feat3": "Aplicações para equipe de desenvolvimento",
    "project.bestdev.feat4": "Produtos e soluções prontos",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Servidor vanilla de Minecraft 1.21.11 com economia. /sell, auction, TPA e sem adições extras - tudo o mais vanilla possível.",
    "project.gridmc.cta": "Entrar no Discord",
    "project.gridmc.feat1": "Economia com /sell e /ah",
    "project.gridmc.feat2": "Sem /spawn e sujeira extra",
    "project.gridmc.feat3": "Um mundo sem regras",
    "project.gridmc.feat4": "Gameplay vanilla máximo",
    "contact.title": "Contato",
    "contact.subtitle": "Entre em contato",
    "contact.heading": "Vamos criar algo **juntos**",
    "contact.text": "Tem um projeto ou quer conversar? Me escreva no Telegram - sempre estou pronto para discutir e implementar seu projeto a um ótimo preço.",
    "contact.button": "Escrever no Telegram",
    "github.title": "Código",
    "github.subtitle": "Repositórios do GitHub",
    "footer.rights": "Todos os direitos reservados.",
    "notFound.title": "Página não encontrada",
    "notFound.text": "Esta página não existe. Pode ter sido movida ou excluída.",
    "notFound.button": "Ir para home",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.services": "Services",
    "nav.projects": "Projets",
    "nav.code": "Code",
    "nav.contacts": "Contacts",
    "hero.greeting": "Salut, je suis",
    "hero.name": "KusokMedi",
    "hero.title": "Développeur / Programmeur",
    "hero.description": "Je crée des sites web, des bots, de l'automatisation et des solutions numériques. Spécialisation : Python, React, Node.js, Linux.",
    "hero.cta": "Ce que je peux faire",
    "terminal.line1": "Je suis KusokMedi :)",
    "terminal.line2": "Développeur prêt à transformer votre idée en code !",
    "terminal.line3": "",
    "terminal.line4": "Je peux créer un Bot, un Site Web ou une Application pour vous,",
    "terminal.line5": "vous aider avec l'hébergement, améliorer votre projet actuel,",
    "terminal.line6": "intégrer l'IA ou d'autres services dans votre produit !",
    "terminal.line7": "",
    "terminal.line8": "Créons quelque chose de cool ensemble !",
    "about.title": "À propos de moi",
    "about.subtitle": "Qui je suis",
    "about.heading": "Je crée des produits numériques qui **comptent**",
    "about.text1": "Je suis un développeur qui ne se limite pas à une seule stack. Sites web, bots Telegram, APIs, infrastructure serveur - je comprends et je fais tout. Je m'adapte rapidement au contexte et je commence à travailler.",
    "about.text2": "Je me spécialise en Python, React, Node.js et Linux. Je prends un projet du concept à la production, en travaillant avec la stack complète. Mon approche : comprendre le problème, choisir les bons outils et construire quelque chose qui fonctionne de manière fiable.",
    "highlight.experience": "Expérience",
    "highlight.experience.value": "3+ ans",
    "highlight.experience.desc": "Développement commercial et travail sur des projets de différentes échelles - des startups aux systèmes volumineux",
    "highlight.projects": "Projets",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Projets terminés dans divers domaines : des bots Telegram à l'infrastructure serveur",
    "highlight.tech": "Technologies",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Langages de programmation, frameworks et outils que je maîtrise à un niveau professionnel",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits sur GitHub pendant tout le temps de développement actif de projets open-source et personnels",
    "services.title": "Services",
    "services.subtitle": "Ce que je fais",
    "services.heading": "Ce que je peux faire **pour vous**",
    "services.description": "Cycle de développement complet - du concept au déploiement. Je travaille avec toute la stack pour créer une solution prête à l'emploi.",
    "service.web.title": "Développement Web",
    "service.web.desc": "Sites web, applications web et panneaux d'administration.",
    "service.web.detail1": "Sites responsifs",
    "service.web.detail2": "Applications web",
    "service.web.detail3": "Panneaux d'administration",
    "service.web.detail4": "Landing pages",
    "service.bots.title": "Développement de Bots",
    "service.bots.desc": "Bots Telegram, bots Discord et automatisation.",
    "service.bots.detail1": "Bots Telegram",
    "service.bots.detail2": "Bots Discord",
    "service.bots.detail3": "Automatisation de chat",
    "service.bots.detail4": "Intégration IA",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, bases de données et logique serveur.",
    "service.backend.detail1": "API REST et GraphQL",
    "service.backend.detail2": "Conception de base de données",
    "service.backend.detail3": "Authentification",
    "service.backend.detail4": "Microservices",
    "service.linux.title": "Linux / Serveurs",
    "service.linux.desc": "Configuration, optimisation et automatisation de serveurs.",
    "service.linux.detail1": "Configuration serveur",
    "service.linux.detail2": "Déploiement Docker",
    "service.linux.detail3": "Pipelines CI/CD",
    "service.linux.detail4": "Monitoring",
    "service.programs.title": "Programmes",
    "service.programs.desc": "Utilitaires, scripts et programmes pour toutes les tâches.",
    "service.programs.detail1": "Outils CLI",
    "service.programs.detail2": "Scripts d'automatisation",
    "service.programs.detail3": "Utilitaires bureau",
    "service.programs.detail4": "Traitement de données",
    "service.audit.title": "Audit et Conseil",
    "service.audit.desc": "Refactoring, optimisation et solutions architecturales.",
    "service.audit.detail1": "Audit de code et de projets",
    "service.audit.detail2": "Optimisation des performances",
    "service.audit.detail3": "Architecture système",
    "service.audit.detail4": "Documentation technique",
    "service.hosting.title": "Hébergement et Déploiement",
    "service.hosting.desc": "Hébergement de vos sites, bots et scripts sur le serveur. Solutions clés en main.",
    "service.hosting.detail1": "Hébergement de scripts et bots prêts",
    "service.hosting.detail2": "Configuration VPS/VDS et hébergement",
    "service.hosting.detail3": "Domaines et certificats SSL",
    "service.hosting.detail4": "Migration de projets",
    "service.support.title": "Support et Maintenance",
    "service.support.desc": "Support technique pour vos projets. Correction rapide des bugs et contrôle de stabilité.",
    "service.support.detail1": "Correction d'erreurs et de bugs",
    "service.support.detail2": "Mise à jour des dépendances et systèmes",
    "service.support.detail3": "Configuration de sauvegardes régulières",
    "service.support.detail4": "Monitoring de disponibilité 24/7",
    "service.api.title": "Intégration d'API et Services",
    "service.api.desc": "Connecter vos sites et programmes avec des systèmes externes pour l'automatisation des processus métier.",
    "service.api.detail1": "Connexion de systèmes de paiement",
    "service.api.detail2": "Intégration CRM (amoCRM, Bitrix24)",
    "service.api.detail3": "Configuration de notifications messenger",
    "service.api.detail4": "Synchronisation Google Sheets",
    "projects.title": "Projets",
    "projects.subtitle": "Mon travail",
    "projects.heading": "Travaux **en vedette**",
    "projects.description": "Projets réels créés de zéro - chacun résout des problèmes spécifiques en utilisant les bonnes technologies.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot pour messages anonymes sur Telegram. Créez votre lien - toute personne qui le suivra pourra vous envoyer un message anonyme.",
    "project.anonspeak.cta": "Ouvrir le bot",
    "project.anonspeak.feat1": "Créez votre lien anonyme",
    "project.anonspeak.feat2": "Répondez aux messages anonymes",
    "project.anonspeak.feat3": "Bloquez les utilisateurs indésirables",
    "project.anonspeak.feat4": "Statistiques des messages",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Bot de support pour le studio Minecraft BestDev. Commandez un plugin, une build, une consultation ou une solution clés en main.",
    "project.bestdev.cta": "Ouvrir le bot",
    "project.bestdev.feat1": "Commandez plugins et builds clés en main",
    "project.bestdev.feat2": "Consultations de projets",
    "project.bestdev.feat3": "Candidatures à l'équipe de développement",
    "project.bestdev.feat4": "Produits et solutions prêts",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Serveur Minecraft vanilla 1.21.11 avec économie. /sell, auction, TPA et sans ajouts supplémentaires - tout le plus vanilla possible.",
    "project.gridmc.cta": "Rejoindre Discord",
    "project.gridmc.feat1": "Économie avec /sell et /ah",
    "project.gridmc.feat2": "Pas de /spawn et de déchet supplémentaire",
    "project.gridmc.feat3": "Un monde sans règles",
    "project.gridmc.feat4": "Gameplay vanilla maximum",
    "contact.title": "Contact",
    "contact.subtitle": "Contactez-moi",
    "contact.heading": "Créons quelque chose **ensemble**",
    "contact.text": "Vous avez un projet ou voulez simplement discuter ? Écrivez-moi sur Telegram - je suis toujours prêt à discuter et à implémenter votre projet à un excellent prix.",
    "contact.button": "Écrire sur Telegram",
    "github.title": "Code",
    "github.subtitle": "Dépôts GitHub",
    "footer.rights": "Tous droits réservés.",
    "notFound.title": "Page non trouvée",
    "notFound.text": "Cette page n'existe pas. Elle a peut-être été déplacée ou supprimée.",
    "notFound.button": "Aller à l'accueil",
  },
  de: {
    "nav.home": "Startseite",
    "nav.about": "Über",
    "nav.services": "Dienstleistungen",
    "nav.projects": "Projekte",
    "nav.code": "Code",
    "nav.contacts": "Kontakte",
    "hero.greeting": "Hallo, ich bin",
    "hero.name": "KusokMedi",
    "hero.title": "Entwickler / Programmierer",
    "hero.description": "Ich erstelle Websites, Bots, Automatisierung und digitale Lösungen. Spezialisierung: Python, React, Node.js, Linux.",
    "hero.cta": "Was ich machen kann",
    "terminal.line1": "Ich bin KusokMedi :)",
    "terminal.line2": "Entwickler, bereit Ihre Idee in Code umzuwandeln!",
    "terminal.line3": "",
    "terminal.line4": "Ich kann für Sie einen Bot, eine Website oder eine Anwendung erstellen,",
    "terminal.line5": "beim Hosting helfen, Ihr aktuelles Projekt verbessern,",
    "terminal.line6": "KI oder andere Dienste in Ihr Produkt integrieren!",
    "terminal.line7": "",
    "terminal.line8": "Lass uns zusammen etwas Cooles erschaffen!",
    "about.title": "Über mich",
    "about.subtitle": "Wer ich bin",
    "about.heading": "Ich erstelle digitale Produkte, die **wichtig sind**",
    "about.text1": "Ich bin ein Entwickler, der sich nicht auf einen einzigen Stack beschränkt. Websites, Telegram-Bots, APIs, Serverinfrastruktur - ich verstehe und mache alles. Ich finde schnell in den Kontext und beginne zu arbeiten.",
    "about.text2": "Ich spezialisiere mich auf Python, React, Node.js und Linux. Ich begleite ein Projekt vom Konzept bis zur Produktion und arbeite mit dem gesamten Stack. Mein Ansatz: das Problem verstehen, die richtigen Tools wählen und etwas Zuverlässiges bauen.",
    "highlight.experience": "Erfahrung",
    "highlight.experience.value": "3+ Jahre",
    "highlight.experience.desc": "Kommerzielle Entwicklung und Arbeit an Projekten verschiedener Größenordnungen - von Startups bis zu großen Systemen",
    "highlight.projects": "Projekte",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Abgeschlossene Projekte in verschiedenen Bereichen: von Telegram-Bots bis zur Serverinfrastruktur",
    "highlight.tech": "Technologien",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "Programmiersprachen, Frameworks und Tools, die ich auf professionellem Niveau beherrsche",
    "highlight.commits": "Commits",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "Commits auf GitHub während der gesamten aktiven Entwicklung von Open-Source- und persönlichen Projekten",
    "services.title": "Dienstleistungen",
    "services.subtitle": "Was ich mache",
    "services.heading": "Was ich **für Sie** machen kann",
    "services.description": "Vollständiger Entwicklungszyklus - vom Konzept bis zum Deployment. Ich arbeite mit dem gesamten Stack, um eine betriebsbereite Lösung zu erstellen.",
    "service.web.title": "Webentwicklung",
    "service.web.desc": "Websites, Webanwendungen und Admin-Panels.",
    "service.web.detail1": "Responsive Websites",
    "service.web.detail2": "Webanwendungen",
    "service.web.detail3": "Admin-Panels",
    "service.web.detail4": "Landing Pages",
    "service.bots.title": "Bot-Entwicklung",
    "service.bots.desc": "Telegram-Bots, Discord-Bots und Automatisierung.",
    "service.bots.detail1": "Telegram-Bots",
    "service.bots.detail2": "Discord-Bots",
    "service.bots.detail3": "Chat-Automatisierung",
    "service.bots.detail4": "KI-Integration",
    "service.backend.title": "Backend",
    "service.backend.desc": "API, Datenbanken und Serverlogik.",
    "service.backend.detail1": "REST- und GraphQL-API",
    "service.backend.detail2": "Datenbankdesign",
    "service.backend.detail3": "Authentifizierung",
    "service.backend.detail4": "Microservices",
    "service.linux.title": "Linux / Server",
    "service.linux.desc": "Serverkonfiguration, Optimierung und Automatisierung.",
    "service.linux.detail1": "Serverkonfiguration",
    "service.linux.detail2": "Docker-Deployment",
    "service.linux.detail3": "CI/CD-Pipelines",
    "service.linux.detail4": "Monitoring",
    "service.programs.title": "Programme",
    "service.programs.desc": "Dienstprogramme, Skripte und Programme für beliebige Aufgaben.",
    "service.programs.detail1": "CLI-Tools",
    "service.programs.detail2": "Automatisierungsskripte",
    "service.programs.detail3": "Desktop-Dienstprogramme",
    "service.programs.detail4": "Datenverarbeitung",
    "service.audit.title": "Audit und Beratung",
    "service.audit.desc": "Refactoring, Optimierung und architektonische Lösungen.",
    "service.audit.detail1": "Code- und Projekt-Audit",
    "service.audit.detail2": "Leistungsoptimierung",
    "service.audit.detail3": "Systemarchitektur",
    "service.audit.detail4": "Technische Dokumentation",
    "service.hosting.title": "Hosting und Deployment",
    "service.hosting.desc": "Hosting Ihrer Websites, Bots und Skripte auf dem Server. schlüsselfertige Lösungen.",
    "service.hosting.detail1": "Hosting fertiger Skripte und Bots",
    "service.hosting.detail2": "VPS/VDS- und Hosting-Einrichtung",
    "service.hosting.detail3": "Domains und SSL-Zertifikate",
    "service.hosting.detail4": "Projektmigration",
    "service.support.title": "Support und Wartung",
    "service.support.desc": "Technischer Support für Ihre Projekte. Schnelle Fehlerbehebung und Stabilitätskontrolle.",
    "service.support.detail1": "Fehler- und Bug-Behebung",
    "service.support.detail2": "Abhängigkeits- und System-Updates",
    "service.support.detail3": "Regelmäßige Backup-Einrichtung",
    "service.support.detail4": "24/7-Verfügbarkeitsüberwachung",
    "service.api.title": "API- und Dienstintegration",
    "service.api.desc": "Ihre Websites und Programme mit externen Systemen für die Automatisierung von Geschäftsprozessen verbinden.",
    "service.api.detail1": "Zahlungssystem-Anbindung",
    "service.api.detail2": "CRM-Integration (amoCRM, Bitrix24)",
    "service.api.detail3": "Messenger-Benachrichtigungseinrichtung",
    "service.api.detail4": "Google Sheets-Synchronisierung",
    "projects.title": "Projekte",
    "projects.subtitle": "Meine Arbeit",
    "projects.heading": "**Ausgewählte** Arbeiten",
    "projects.description": "Echte Projekte von Grund auf erstellt - jedes löst spezifische Probleme mit den richtigen Technologien.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Bot für anonyme Nachrichten in Telegram. Erstellen Sie Ihren Link - jeder, der ihm folgt, kann Ihnen eine anonyme Nachricht senden.",
    "project.anonspeak.cta": "Bot öffnen",
    "project.anonspeak.feat1": "Erstellen Sie Ihren anonymen Link",
    "project.anonspeak.feat2": "Anonymen Nachrichten antworten",
    "project.anonspeak.feat3": "Unerwünschte Benutzer blockieren",
    "project.anonspeak.feat4": "Nachrichtenstatistiken",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Support-Bot für Minecraft-Studio BestDev. Bestellen Sie Plugins, Builds, Beratung oder schlüsselfertige Lösungen.",
    "project.bestdev.cta": "Bot öffnen",
    "project.bestdev.feat1": "Plugins und Builds schlüsselfertig bestellen",
    "project.bestdev.feat2": "Projektberatungen",
    "project.bestdev.feat3": "Bewerbungen ans Entwicklungsteam",
    "project.bestdev.feat4": "Fertige Produkte und Lösungen",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "Vanilla Minecraft-Server 1.21.11 mit Wirtschaft. /sell, Auktion, TPA und keine zusätzlichen Addons - alles so vanilla wie möglich.",
    "project.gridmc.cta": "Discord beitreten",
    "project.gridmc.feat1": "Wirtschaft mit /sell und /ah",
    "project.gridmc.feat2": "Kein /spawn und额外 junk",
    "project.gridmc.feat3": "Eine Welt ohne Regeln",
    "project.gridmc.feat4": "Maximaler Vanilla-Gameplay",
    "contact.title": "Kontakt",
    "contact.subtitle": "Kontakt aufnehmen",
    "contact.heading": "Lass uns etwas **zusammen** erschaffen",
    "contact.text": "Haben Sie ein Projekt oder möchten Sie einfach chatten? Schreiben Sie mir auf Telegram - ich bin immer bereit, Ihr Projekt zu einem great Preis zu besprechen und umzusetzen.",
    "contact.button": "Auf Telegram schreiben",
    "github.title": "Code",
    "github.subtitle": "GitHub-Repositories",
    "footer.rights": "Alle Rechte vorbehalten.",
    "notFound.title": "Seite nicht gefunden",
    "notFound.text": "Diese Seite existiert nicht. Sie wurde möglicherweise verschoben oder gelöscht.",
    "notFound.button": "Nach Hause gehen",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.about": "概要",
    "nav.services": "サービス",
    "nav.projects": "プロジェクト",
    "nav.code": "コード",
    "nav.contacts": "連絡先",
    "hero.greeting": "こんにちは、私は",
    "hero.name": "KusokMedi",
    "hero.title": "開発者 / プログラマー",
    "hero.description": "ウェブサイト、ボット、自動化、ソリューションを作成します。専門：Python、React、Node.js、Linux。",
    "hero.cta": "我能做什么",
    "terminal.line1": "私はKusokMediです :)",
    "terminal.line2": "あなたのアイデアをコードに変える準備ができた開発者です！",
    "terminal.line3": "",
    "terminal.line4": "ボット、ウェブサイト、アプリケーションを作成できます、",
    "terminal.line5": "ホスティング、お金の管理、既存プロジェクトの改善、",
    "terminal.line6": "AI或其他サービスをプロダクトに統合！",
    "terminal.line7": "",
    "terminal.line8": "一緒にクールなものを作りましょう！",
    "about.title": "私について",
    "about.subtitle": "私は誰ですか",
    "about.heading": "私は**重要な**デジタル製品を作成します",
    "about.text1": "私は1つのスタックに限定されない開発者です。ウェブサイト、Telegramボット、API、サーバーインフラストラクチャ - すべて理解して実装します。素早くコンテキストを把握して作業を開始します。",
    "about.text2": "Python、React、Node.js、Linuxを専門としています。コンセプトから本番までプロジェクトを担当し、フルスタックで動作します。私のアプローチ：問題を理解し、適切なツールを選び、確実に動作するものを構築します。",
    "highlight.experience": "経験",
    "highlight.experience.value": "3+年",
    "highlight.experience.desc": "商業開発とさまざまな規模のプロジェクトでの作業 - スタートアップから大規模システムまで",
    "highlight.projects": "プロジェクト",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "さまざまな分野で完了したプロジェクト：Telegramボットからサーバーインフラストラクチャまで",
    "highlight.tech": "技術",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "プロフェッショナルレベルで習熟しているプログラミング言語、フレームワーク、ツール",
    "highlight.commits": "コミット",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "アクティブなオープンソースと個人プロジェクトの全開発期間中のGitHubへのコミット",
    "services.title": "サービス",
    "services.subtitle": "何をしているか",
    "services.heading": "私に**できますか**",
    "services.description": "完全な開発サイクル - コンセプトからデプロイまで。すぐに使えるソリューションを作成するためにフルスタックで作業します。",
    "service.web.title": "ウェブ開発",
    "service.web.desc": "ウェブサイト、ウェブアプリケーション、管理パネル。",
    "service.web.detail1": "レスポンシブウェブサイト",
    "service.web.detail2": "ウェブアプリケーション",
    "service.web.detail3": "管理パネル",
    "service.web.detail4": "ランディングページ",
    "service.bots.title": "ボット開発",
    "service.bots.desc": "Telegramボット、Discordボット、自動化。",
    "service.bots.detail1": "Telegramボット",
    "service.bots.detail2": "Discordボット",
    "service.bots.detail3": "チャット自動化",
    "service.bots.detail4": "AI統合",
    "service.backend.title": "バックエンド",
    "service.backend.desc": "API、データベース、サーバーロジック。",
    "service.backend.detail1": "RESTおよびGraphQL API",
    "service.backend.detail2": "データベース設計",
    "service.backend.detail3": "認証",
    "service.backend.detail4": "マイクロサービス",
    "service.linux.title": "Linux / サーバー",
    "service.linux.desc": "サーバー構成、最適化、自動化。",
    "service.linux.detail1": "サーバー構成",
    "service.linux.detail2": "Dockerデプロイ",
    "service.linux.detail3": "CI/CDパイプライン",
    "service.linux.detail4": "監視",
    "service.programs.title": "プログラム",
    "service.programs.desc": "任意のタスクのためのユーティリティ、スクリプト、プログラム。",
    "service.programs.detail1": "CLIツール",
    "service.programs.detail2": "自動化スクリプト",
    "service.programs.detail3": "デスクトップユーティリティ",
    "service.programs.detail4": "データ処理",
    "service.audit.title": "監査とコンサルティング",
    "service.audit.desc": "リファクタリング、最適化、アーキテクチャソリューション。",
    "service.audit.detail1": "コードとプロジェクトの監査",
    "service.audit.detail2": "パフォーマンス最適化",
    "service.audit.detail3": "システムアーキテクチャ",
    "service.audit.detail4": "技術文書",
    "service.hosting.title": "ホスティングとデプロイ",
    "service.hosting.desc": "サーバー上のサイト、ボット、スクリプトのホスティング。一括ソリューションの起動。",
    "service.hosting.detail1": "完成したスクリプトとボットのホスティング",
    "service.hosting.detail2": "VPS/VDSとホスティングのセットアップ",
    "service.hosting.detail3": "ドメインとSSL証明書",
    "service.hosting.detail4": "プロジェクトの移行",
    "service.support.title": "サポートとメンテナンス",
    "service.support.desc": "プロジェクトのテクニカルサポート。迅速なバグ修正と安定性の制御。",
    "service.support.detail1": "エラーとバグの修正",
    "service.support.detail2": "依存関係とシステムの更新",
    "service.support.detail3": "定期的なバックアップの設定",
    "service.support.detail4": "24/7可用性監視",
    "service.api.title": "APIとサービスの統合",
    "service.api.desc": "ビジネスプロセスの自動化のために、あなたのサイトやプログラムを外部システムに接続します。",
    "service.api.detail1": "決済システムの接続",
    "service.api.detail2": "CRM統合 (amoCRM, Bitrix24)",
    "service.api.detail3": "メッセンジャー通知の設定",
    "service.api.detail4": "Googleシートの同期",
    "projects.title": "プロジェクト",
    "projects.subtitle": "私の仕事",
    "projects.heading": "**特筆**作品",
    "projects.description": "ゼロから作成された実際のプロジェクト - それぞれが適切な技術を使用して特定の問題を解決します。",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Telegramで匿名メッセージ用のボット。あなたのリンクを作成 - それに続く人都があなたに匿名メッセージを送ることができます。",
    "project.anonspeak.cta": "ボットを開く",
    "project.anonspeak.feat1": "あなたの匿名リンクを作成",
    "project.anonspeak.feat2": "匿名のメッセージに返信",
    "project.anonspeak.feat3": "不要なユーザーをブロック",
    "project.anonspeak.feat4": "メッセージ統計",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "MinecraftスタジオBestDevのサポートボット。プラグイン、ビルド、コンサルティング、または一括ソリューションを注文できます。",
    "project.bestdev.cta": "ボットを開く",
    "project.bestdev.feat1": "一括でプラグインとビルドを注文",
    "project.bestdev.feat2": "プロジェクトコンサルティング",
    "project.bestdev.feat3": "開発チームへの応募",
    "project.bestdev.feat4": "完成产品和解决方案",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "経済システムを備えたバニラMinecraftサーバー1.21.11。/sell、オークション、TPA、追加のアドオンなし - 可能な限りバニラ。",
    "project.gridmc.cta": "Discordに参加",
    "project.gridmc.feat1": "/sellと/ahでの経済",
    "project.gridmc.feat2": "/spawnと追加のゴミなし",
    "project.gridmc.feat3": "ルールのない1つの世界",
    "project.gridmc.feat4": "最大バニラゲームプレイ",
    "contact.title": "連絡先",
    "contact.subtitle": "お問い合わせ",
    "contact.heading": "一緒に何か**を作成しましょう**",
    "contact.text": "プロジェクトがありますか、それとも単にチャットしたいですか？Telegramで私に書いてください - 常優れた価格であなたのプロジェクトを議論し、実装する準備ができています。",
    "contact.button": "Telegramで書く",
    "github.title": "コード",
    "github.subtitle": "GitHubリポジトリ",
    "footer.rights": "全著作権所有。",
    "notFound.title": "ページが見つかりません",
    "notFound.text": "この상은存在しません。移動または削除された可能性があります。",
    "notFound.button": "ホームに戻る",
  },
  ko: {
    "nav.home": "홈",
    "nav.about": "정보",
    "nav.services": "서비스",
    "nav.projects": "프로젝트",
    "nav.code": "코드",
    "nav.contacts": "연락처",
    "hero.greeting": "안녕하세요, 저는",
    "hero.name": "KusokMedi",
    "hero.title": "개발자 / 프로그래머",
    "hero.description": "웹사이트, 봇, 자동화 및 디지털 솔루션을 만들습니다. 전문 분야: Python, React, Node.js, Linux.",
    "hero.cta": "내가 할 수 있는 것",
    "terminal.line1": "저는 KusokMedi입니다 :)",
    "terminal.line2": "아이디어를 코드로 바꿀 준비가 된 개발자입니다!",
    "terminal.line3": "",
    "terminal.line4": "봇, 웹사이트 또는 애플리케이션을 만들어 드릴 수 있습니다,",
    "terminal.line5": "호스팅 도움, 현재 프로젝트 개선,",
    "terminal.line6": "AI或其他 서비스를 제품에 통합!",
    "terminal.line7": "",
    "terminal.line8": "함께 멋진 것을 만들어 봅시다!",
    "about.title": "정보",
    "about.subtitle": "저는 누구인가요",
    "about.heading": "저는**중요한** 디지털 제품을 만듭니다",
    "about.text1": "저는 하나의 스택에 국한되지 않는 개발자입니다. 웹사이트, Telegram 봇, API, 서버 인프라 - 모든 것을 이해하고 구현합니다. 빠르게 맥락을 파악하고 작업에 착수합니다.",
    "about.text2": "Python, React, Node.js, Linux를 전문으로 합니다. 컨셉에서 프로덕션까지 프로젝트를 수행하며 전체 스택으로 작업합니다. 저의 접근 방식: 문제를 이해하고, 올바른 도구를 선택하고, 안정적으로 작동하는 것을 구축합니다.",
    "highlight.experience": "경험",
    "highlight.experience.value": "3+년",
    "highlight.experience.desc": "스타트업부터 대규모 시스템까지 다양한 규모의 프로젝트에서 상업적 개발 및 작업",
    "highlight.projects": "프로젝트",
    "highlight.projects.value": "25+",
    "highlight.projects.desc": "Telegram 봇부터 서버 인프라까지 다양한 분야에 완료된 프로젝트",
    "highlight.tech": "기술",
    "highlight.tech.value": "20+",
    "highlight.tech.desc": "프로фессиональ 수준으로 마스터한 프로그래밍 언어, 프레임워크, 도구",
    "highlight.commits": "커밋",
    "highlight.commits.value": "200+",
    "highlight.commits.desc": "활발한 오픈소스 및 개인 프로젝트 개발 기간 동안의 GitHub 커밋",
    "services.title": "서비스",
    "services.subtitle": "내가 하는 일",
    "services.heading": "내가**당신에게** 할 수 있는 것",
    "services.description": "컨셉에서 디플로이까지 완전한 개발 사이클. 즉시 사용 가능한 솔루션을 만들기 위해 전체 스택으로 작업합니다.",
    "service.web.title": "웹 개발",
    "service.web.desc": "웹사이트, 웹 애플리케이션, 관리자 패널.",
    "service.web.detail1": "반응형 웹사이트",
    "service.web.detail2": "웹 애플리케이션",
    "service.web.detail3": "관리자 패널",
    "service.web.detail4": "랜딩 페이지",
    "service.bots.title": "봇 개발",
    "service.bots.desc": "Telegram 봇, Discord 봇, 자동화.",
    "service.bots.detail1": "Telegram 봇",
    "service.bots.detail2": "Discord 봇",
    "service.bots.detail3": "채팅 자동화",
    "service.bots.detail4": "AI 통합",
    "service.backend.title": "백엔드",
    "service.backend.desc": "API, 데이터베이스, 서버 로직.",
    "service.backend.detail1": "REST 및 GraphQL API",
    "service.backend.detail2": "데이터베이스 설계",
    "service.backend.detail3": "인증",
    "service.backend.detail4": "마이크로서비스",
    "service.linux.title": "Linux / 서버",
    "service.linux.desc": "서버 구성, 최적화, 자동화.",
    "service.linux.detail1": "서버 구성",
    "service.linux.detail2": "Docker 디플로이",
    "service.linux.detail3": "CI/CD 파이프라인",
    "service.linux.detail4": "모니터링",
    "service.programs.title": "프로그램",
    "service.programs.desc": "모든 작업을 위한 유틸리티, 스크립트, 프로그램.",
    "service.programs.detail1": "CLI 도구",
    "service.programs.detail2": "자동화 스크립트",
    "service.programs.detail3": "데스크톱 유틸리티",
    "service.programs.detail4": "데이터 처리",
    "service.audit.title": "감사 및 컨설팅",
    "service.audit.desc": "리팩토링, 최적화, 아키텍처 솔루션.",
    "service.audit.detail1": "코드 및 프로젝트 감사",
    "service.audit.detail2": "성능 최적화",
    "service.audit.detail3": "시스템 아키텍처",
    "service.audit.detail4": "기술 문서",
    "service.hosting.title": "호스팅 및 디플로이",
    "service.hosting.desc": "서버에서 사이트, 봇, 스크립트 호스팅. 턴키 솔루션 시작.",
    "service.hosting.detail1": "완성된 스크립트 및 봇 호스팅",
    "service.hosting.detail2": "VPS/VDS 및 호스팅 설정",
    "service.hosting.detail3": "도메인 및 SSL 인증서",
    "service.hosting.detail4": "프로젝트 마이그레이션",
    "service.support.title": "지원 및 유지보수",
    "service.support.desc": "프로젝트에 대한 기술 지원. 신속한 버그 수정 및 안정성 제어.",
    "service.support.detail1": "오류 및 버그 수정",
    "service.support.detail2": "종속성 및 시스템 업데이트",
    "service.support.detail3": "정기 백업 설정",
    "service.support.detail4": "24/7 가용성 모니터링",
    "service.api.title": "API 및 서비스 통합",
    "service.api.desc": "비즈니스 프로세스 자동화를 위해 사이트와 프로그램을 외부 시스템에 연결합니다.",
    "service.api.detail1": "결제 시스템 연결",
    "service.api.detail2": "CRM 통합 (amoCRM, Bitrix24)",
    "service.api.detail3": "메신저 알림 설정",
    "service.api.detail4": "Google Sheets 동기화",
    "projects.title": "프로젝트",
    "projects.subtitle": "내 작업",
    "projects.heading": "**특정** 작품",
    "projects.description": "처음부터 만든 실제 프로젝트 - 각각이 올바른 기술을 사용하여 특정 문제를 해결합니다.",
    "project.anonspeak.title": "AnonSpeak",
    "project.anonspeak.desc": "Telegram에서 익명 메시지를 위한 봇. 링크를 생성하면 모든 사용자가 익명 메시지를 보낼 수 있습니다.",
    "project.anonspeak.cta": "봇 열기",
    "project.anonspeak.feat1": "익명 링크 생성",
    "project.anonspeak.feat2": "익명 메시지에 답장",
    "project.anonspeak.feat3": "원치 않는 사용자 차단",
    "project.anonspeak.feat4": "메시지 통계",
    "project.bestdev.title": "BestDev Support Bot",
    "project.bestdev.desc": "Minecraft 스튜디오 BestDev용 지원 봇. 플러그인, 빌드, 컨설팅 또는 턴키 솔루션을 주문하세요.",
    "project.bestdev.cta": "봇 열기",
    "project.bestdev.feat1": "턴키로 플러그인 및 빌드 주문",
    "project.bestdev.feat2": "프로젝트 컨설팅",
    "project.bestdev.feat3": "개발 팀 신청",
    "project.bestdev.feat4": "완성된 제품 및 솔루션",
    "project.gridmc.title": "GridMC",
    "project.gridmc.desc": "경제 시스템이 있는 바닐라 Minecraft 서버 1.21.11. /sell, 경매, TPA, 추가 애드온 없음 - 가능한 한 바닐라.",
    "project.gridmc.cta": "Discord 참가",
    "project.gridmc.feat1": "/sell 및 /ah로 경제",
    "project.gridmc.feat2": "/spawn 및 추가 정크 없음",
    "project.gridmc.feat3": "규칙 없는 하나의 세계",
    "project.gridmc.feat4": "최대 바닐라 게임플레이",
    "contact.title": "연락처",
    "contact.subtitle": "문의하기",
    "contact.heading": "함께 무언가**만들어** 봅시다",
    "contact.text": "프로젝트가 있거나 그냥聊하고 싶으신가요? Telegram으로 저에게 쓰세요 - 항상 훌륭한 가격으로 프로젝트를 논의하고 구현할 준비가 되어 있습니다.",
    "contact.button": "Telegram으로 쓰기",
    "github.title": "코드",
    "github.subtitle": "GitHub 저장소",
    "footer.rights": "모든 권리 보유.",
    "notFound.title": "페이지를 찾을 수 없습니다",
    "notFound.text": "이 페이지는 존재하지 않습니다. 이동 또는 삭제되었을 수 있습니다.",
    "notFound.button": "홈으로 가기",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");
  const [contentOpacity, setContentOpacity] = useState(true);

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language | null;
    if (saved) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setContentOpacity(false);
    setTimeout(() => {
      setLangState(newLang);
      localStorage.setItem("lang", newLang);
      setTimeout(() => setContentOpacity(true), 100);
    }, 500);
  };

  const t = (key: string): string => {
    const value = translations[lang]?.[key];
    return value !== undefined ? value : translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      <div
        className={`transition-opacity duration-500 ${contentOpacity ? "opacity-100" : "opacity-0"}`}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
